"""requirement analyses and provenance

Adds requirement_analyses (append-only: the raw input exactly as written, its SHA-256, the engine
version and the result) and the provenance of promoted requirements: origin_analysis_id and
origin_candidate_key, both or neither, the analysis in the same project (composite foreign key),
and at most one live requirement per candidate (a retried promotion cannot duplicate it).
Existing requirements have no origin; no row is rewritten.

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 20:07:47.602019+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirement_analyses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("raw_input", sa.Text(), nullable=False),
        sa.Column("input_sha256", sa.Text(), nullable=False),
        sa.Column("engine_version", sa.Text(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "input_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_requirement_analyses_input_sha256_format")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(result) = 'object'", name=op.f("ck_requirement_analyses_result_object")
        ),
        sa.CheckConstraint(
            "char_length(engine_version) BETWEEN 1 AND 100",
            name=op.f("ck_requirement_analyses_engine_version_length"),
        ),
        sa.CheckConstraint(
            "char_length(raw_input) BETWEEN 1 AND 20000",
            name=op.f("ck_requirement_analyses_raw_input_length"),
        ),
        sa.CheckConstraint(
            "octet_length(result::text) <= 4194304", name=op.f("ck_requirement_analyses_result_size")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirement_analyses_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_analyses")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_requirement_analyses_id_project_id")),
    )
    op.create_index(
        op.f("ix_requirement_analyses_project_id_created_at_id"),
        "requirement_analyses",
        ["project_id", "created_at", "id"],
        unique=False,
    )
    op.add_column("requirements", sa.Column("origin_analysis_id", sa.Uuid(), nullable=True))
    op.add_column("requirements", sa.Column("origin_candidate_key", sa.Text(), nullable=True))
    op.create_index(
        "uq_requirements_origin_live",
        "requirements",
        ["origin_analysis_id", "origin_candidate_key"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND origin_analysis_id IS NOT NULL"),
    )
    op.create_foreign_key(
        "fk_requirements_origin_requirement_analyses",
        "requirements",
        "requirement_analyses",
        ["origin_analysis_id", "project_id"],
        ["id", "project_id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_requirements_origin_complete"),
        "requirements",
        "(origin_analysis_id IS NULL) = (origin_candidate_key IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_requirements_origin_candidate_key_format"),
        "requirements",
        "origin_candidate_key IS NULL OR origin_candidate_key ~ '^cand_[0-9a-f]{16}$'",
    )
    # Append-only, with the guard function created for requirement sets (revision 0004).
    op.execute(
        """
        CREATE TRIGGER requirement_analyses_append_only
        BEFORE UPDATE OR DELETE ON requirement_analyses
        FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()
        """
    )
    op.execute(
        """
        CREATE TRIGGER requirement_analyses_no_truncate
        BEFORE TRUNCATE ON requirement_analyses
        FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER requirement_analyses_no_truncate ON requirement_analyses")
    op.execute("DROP TRIGGER requirement_analyses_append_only ON requirement_analyses")
    op.drop_constraint(op.f("ck_requirements_origin_candidate_key_format"), "requirements", type_="check")
    op.drop_constraint(op.f("ck_requirements_origin_complete"), "requirements", type_="check")
    op.drop_constraint("fk_requirements_origin_requirement_analyses", "requirements", type_="foreignkey")
    op.drop_index(
        "uq_requirements_origin_live",
        table_name="requirements",
        postgresql_where=sa.text("deleted_at IS NULL AND origin_analysis_id IS NOT NULL"),
    )
    op.drop_column("requirements", "origin_candidate_key")
    op.drop_column("requirements", "origin_analysis_id")
    op.drop_index(op.f("ix_requirement_analyses_project_id_created_at_id"), table_name="requirement_analyses")
    op.drop_table("requirement_analyses")
    # ### end Alembic commands ###
