"""validation runs and findings

A validation run records one execution of the deterministic validation engine against one
architecture revision: the rule set, fingerprints, summary, requirement verdicts, rule failures,
limitations and the inputs it was given (configuration, policy, requirement versions). Its
findings are rows of their own, in the run's canonical order, for filtering and paging.

Both tables are append-only (triggers, with the guard function of requirement sets, 0004): a run is
stored once, completed or failed. Runs reference their architecture and revision through
same-project foreign keys, and findings their run the same way.

Downgrading removes both tables and every stored run with them.

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-26 16:00:00+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validation_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("revision_content_hash", sa.Text(), nullable=False),
        sa.Column("profile", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rule_set", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context_fingerprint", sa.Text(), nullable=True),
        sa.Column("result_fingerprint", sa.Text(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("requirement_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failures", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(inputs) = 'object'", name=op.f("ck_validation_runs_inputs_object")),
        sa.CheckConstraint(
            "revision_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_validation_runs_revision_content_hash_format"),
        ),
        sa.CheckConstraint(
            "status <> 'completed' OR (completed_at IS NOT NULL AND result_fingerprint IS NOT NULL AND summary IS NOT NULL AND rule_set IS NOT NULL)",
            name=op.f("ck_validation_runs_completed_has_result"),
        ),
        sa.CheckConstraint(
            "status <> 'failed' OR (completed_at IS NOT NULL AND error_code IS NOT NULL)",
            name=op.f("ck_validation_runs_failed_has_error"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'failed')", name=op.f("ck_validation_runs_status")
        ),
        sa.CheckConstraint(
            "char_length(profile) BETWEEN 1 AND 64", name=op.f("ck_validation_runs_profile_length")
        ),
        sa.CheckConstraint("revision_number >= 1", name=op.f("ck_validation_runs_revision_number_positive")),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_validation_runs_architecture_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_validation_runs_revision_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_runs")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_validation_runs_id_project_id")),
    )
    op.create_index(
        op.f("ix_validation_runs_architecture_id_requested_at_id"),
        "validation_runs",
        ["architecture_id", "requested_at", "id"],
        unique=False,
    )
    op.create_table(
        "validation_findings",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.Text(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("blocking", sa.Boolean(), nullable=False),
        sa.Column("entity_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "category IN ('structure', 'configuration', 'completeness', 'policy', 'requirements')",
            name=op.f("ck_validation_findings_category"),
        ),
        sa.CheckConstraint("jsonb_typeof(data) = 'object'", name=op.f("ck_validation_findings_data_object")),
        sa.CheckConstraint(
            "jsonb_typeof(entity_ids) = 'array'", name=op.f("ck_validation_findings_entity_ids_array")
        ),
        sa.CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low', 'info')",
            name=op.f("ck_validation_findings_severity"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_validation_findings_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["run_id", "project_id"],
            ["validation_runs.id", "validation_runs.project_id"],
            name="fk_validation_findings_run_validation_runs",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_findings")),
        sa.UniqueConstraint("run_id", "finding_id", name=op.f("uq_validation_findings_run_id_finding_id")),
        sa.UniqueConstraint("run_id", "position", name=op.f("uq_validation_findings_run_id_position")),
    )
    for table in ("validation_runs", "validation_findings"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()"
        )


def downgrade() -> None:
    for table in ("validation_findings", "validation_runs"):
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    op.drop_table("validation_findings")
    op.drop_index(op.f("ix_validation_runs_architecture_id_requested_at_id"), table_name="validation_runs")
    op.drop_table("validation_runs")
