"""evolution analyses and decisions

An evolution analysis records typed goals evaluated against one architecture revision: the request's
inputs (goals, constraints, scope, cited evidence, assumptions), the requirements read, the policy,
provider and currency; the rule and engine versions, the fingerprint and summary; the goals, the
findings (stale or missing evidence, unsupported goals, structural considerations, ...), the evidence
considered (each stored analysis with its revision, content hash and model version) and the
limitations. Its candidates are rows of their own, for paging and filtering, in canonical order: each
a proposal of configuration changes with its evidence, validation, impacts and trade-offs. Nothing is
applied to the architecture, and the architecture is never copied.

Both evolution tables are append-only (triggers, with the guard function of requirement sets, 0004).

A decision (ADR-<number>, unique per project) records the options considered (candidate snapshots),
its source analysis and baseline, and a person's decision. It is updated through its lifecycle
(proposed, accepted or rejected, superseded, linked to the revision a person says implements it),
every change audited; decisions reference their architecture, successor and resulting revision
through same-project foreign keys.

Downgrading removes the three tables and every stored evolution analysis and decision with them.

Revision ID: 0019
Revises: 0018
Create Date: 2026-09-27 17:42:17.838432+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

TABLES = ("evolution_analyses", "evolution_candidates")  # append-only

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decisions",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("goals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("related_element_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("chosen_option", sa.Text(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_by", sa.Uuid(), nullable=True),
        sa.Column("resulting_revision_number", sa.Integer(), nullable=True),
        sa.Column("resulting_content_hash", sa.Text(), nullable=True),
        sa.Column("linked_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'proposed') = (decided_at IS NULL)", name=op.f("ck_decisions_decided_unless_proposed")
        ),
        sa.CheckConstraint(
            "(status = 'superseded') = (superseded_by IS NOT NULL)",
            name=op.f("ck_decisions_superseded_has_successor"),
        ),
        sa.CheckConstraint("jsonb_typeof(options) = 'array'", name=op.f("ck_decisions_options_array")),
        sa.CheckConstraint(
            "status IN ('proposed', 'accepted', 'rejected', 'superseded')", name=op.f("ck_decisions_status")
        ),
        sa.CheckConstraint(
            "status NOT IN ('accepted', 'superseded') OR chosen_option IS NOT NULL",
            name=op.f("ck_decisions_accepted_has_option"),
        ),
        sa.CheckConstraint(
            "(resulting_revision_number IS NULL) = (linked_at IS NULL)",
            name=op.f("ck_decisions_link_complete"),
        ),
        sa.CheckConstraint("char_length(title) BETWEEN 1 AND 200", name=op.f("ck_decisions_title_length")),
        sa.CheckConstraint("number >= 1", name=op.f("ck_decisions_number_positive")),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_decisions_architecture_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "resulting_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_decisions_resulting_revision_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by", "project_id"],
            ["decisions.id", "decisions.project_id"],
            name="fk_decisions_superseded_by_decisions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decisions")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_decisions_id_project_id")),
        sa.UniqueConstraint("project_id", "number", name=op.f("uq_decisions_project_id_number")),
    )
    op.create_table(
        "evolution_analyses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("revision_content_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_set", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_fingerprint", sa.Text(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("goals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(findings) = 'array'", name=op.f("ck_evolution_analyses_findings_array")
        ),
        sa.CheckConstraint("jsonb_typeof(goals) = 'array'", name=op.f("ck_evolution_analyses_goals_array")),
        sa.CheckConstraint(
            "jsonb_typeof(inputs) = 'object'", name=op.f("ck_evolution_analyses_inputs_object")
        ),
        sa.CheckConstraint(
            "revision_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_evolution_analyses_revision_content_hash_format"),
        ),
        sa.CheckConstraint(
            "status <> 'failed' OR (completed_at IS NOT NULL AND error_code IS NOT NULL)",
            name=op.f("ck_evolution_analyses_failed_has_error"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'partial', 'insufficient_evidence', 'failed')",
            name=op.f("ck_evolution_analyses_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'failed') OR (completed_at IS NOT NULL AND result_fingerprint IS NOT NULL AND summary IS NOT NULL AND model_set IS NOT NULL)",
            name=op.f("ck_evolution_analyses_finished_has_result"),
        ),
        sa.CheckConstraint(
            "label IS NULL OR char_length(label) BETWEEN 1 AND 100",
            name=op.f("ck_evolution_analyses_label_length"),
        ),
        sa.CheckConstraint(
            "revision_number >= 1", name=op.f("ck_evolution_analyses_revision_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_evolution_analyses_architecture_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_evolution_analyses_revision_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evolution_analyses")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_evolution_analyses_id_project_id")),
    )
    op.create_index(
        op.f("ix_evolution_analyses_architecture_id_requested_at_id"),
        "evolution_analyses",
        ["architecture_id", "requested_at", "id"],
        unique=False,
    )
    op.create_table(
        "evolution_candidates",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Text(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("validation", sa.Text(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "candidate_id ~ '^evo_[0-9a-f]{20}$'", name=op.f("ck_evolution_candidates_candidate_id_format")
        ),
        sa.CheckConstraint(
            "category IN ('scaling', 'redundancy', 'security_control', 'instrumentation')",
            name=op.f("ck_evolution_candidates_category"),
        ),
        sa.CheckConstraint("jsonb_typeof(data) = 'object'", name=op.f("ck_evolution_candidates_data_object")),
        sa.CheckConstraint(
            "validation IN ('not_validated', 'valid', 'invalid', 'not_evaluable', 'unsupported')",
            name=op.f("ck_evolution_candidates_validation"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_evolution_candidates_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["analysis_id", "project_id"],
            ["evolution_analyses.id", "evolution_analyses.project_id"],
            name="fk_evolution_candidates_analysis_evolution_analyses",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evolution_candidates")),
        sa.UniqueConstraint(
            "analysis_id", "candidate_id", name=op.f("uq_evolution_candidates_analysis_id_candidate_id")
        ),
        sa.UniqueConstraint(
            "analysis_id", "position", name=op.f("uq_evolution_candidates_analysis_id_position")
        ),
    )
    # ### end Alembic commands ###
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()"
        )


def downgrade() -> None:
    for table in reversed(TABLES):
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evolution_candidates")
    op.drop_index(
        op.f("ix_evolution_analyses_architecture_id_requested_at_id"), table_name="evolution_analyses"
    )
    op.drop_table("evolution_analyses")
    op.drop_table("decisions")
    # ### end Alembic commands ###
