"""drift detection

A drift analysis compares one exact architecture revision with one stored discovery run (both
referenced by same-project foreign keys; a discovery run an analysis compared cannot be deleted) and
records the result — compatibility, coverage, findings with their evidence and impact context — or
why it failed. Drift items follow a difference across an architecture's analyses and carry its
review; identity mappings record the identities people confirmed.

Analyses and identity mappings are append-only. An item's identity never changes, it is never
deleted, and its review history only grows: triggers refuse anything else, and truncation.
Nothing here writes an architecture revision.

Downgrading removes the tables and every stored drift analysis, item and mapping with them.

Revision ID: 0022
Revises: 0021
Create Date: 2026-10-02 12:09:33.468274+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0022"
down_revision: str | None = "0021"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_discovery_runs_id_project_id"), "discovery_runs", ["id", "project_id"]
    )
    op.create_table(
        "drift_identity_mappings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_id", sa.Text(), nullable=False),
        sa.Column("discovered_key", sa.Text(), nullable=True),
        sa.Column("confirmed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "char_length(baseline_id) BETWEEN 1 AND 128",
            name=op.f("ck_drift_identity_mappings_baseline_id_length"),
        ),
        sa.CheckConstraint(
            "discovered_key IS NULL OR char_length(discovered_key) BETWEEN 1 AND 128",
            name=op.f("ck_drift_identity_mappings_discovered_key_length"),
        ),
        sa.CheckConstraint(
            "note IS NULL OR char_length(note) BETWEEN 1 AND 2000",
            name=op.f("ck_drift_identity_mappings_note_length"),
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_drift_identity_mappings_architectures",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drift_identity_mappings")),
    )
    op.create_index(
        "ix_drift_identity_mappings_architecture",
        "drift_identity_mappings",
        ["architecture_id", "confirmed_at"],
        unique=False,
    )
    op.create_table(
        "drift_analyses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("baseline_revision_number", sa.Integer(), nullable=False),
        sa.Column("discovery_run_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("summary", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("fingerprint", sa.Text(), nullable=True),
        sa.Column("error", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'failed') = (error IS NOT NULL)", name=op.f("ck_drift_analyses_error_when_failed")
        ),
        sa.CheckConstraint(
            "(status IN ('completed', 'completed_with_warnings', 'incompatible_inputs')) = (result IS NOT NULL AND summary IS NOT NULL AND fingerprint IS NOT NULL)",
            name=op.f("ck_drift_analyses_result_when_compared"),
        ),
        sa.CheckConstraint(
            "fingerprint IS NULL OR fingerprint ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_drift_analyses_fingerprint_format"),
        ),
        sa.CheckConstraint("jsonb_typeof(request) = 'object'", name=op.f("ck_drift_analyses_request_object")),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'completed_with_warnings', 'failed', 'cancelled', 'incompatible_inputs')",
            name=op.f("ck_drift_analyses_status"),
        ),
        sa.CheckConstraint("baseline_revision_number >= 1", name=op.f("ck_drift_analyses_revision_positive")),
        sa.CheckConstraint(
            "result IS NULL OR octet_length(result::text) <= 33554432",
            name=op.f("ck_drift_analyses_result_size"),
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "baseline_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_drift_analyses_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_drift_analyses_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id", "project_id"],
            ["discovery_runs.id", "discovery_runs.project_id"],
            name="fk_drift_analyses_discovery_runs",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_drift_analyses_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drift_analyses")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_drift_analyses_id_project_id")),
    )
    op.create_index(
        "ix_drift_analyses_architecture", "drift_analyses", ["architecture_id", "requested_at"], unique=False
    )
    op.create_index("ix_drift_analyses_discovery_run", "drift_analyses", ["discovery_run_id"], unique=False)
    op.create_index(
        "ix_drift_analyses_project_listing",
        "drift_analyses",
        ["project_id", "requested_at", "id"],
        unique=False,
    )
    op.create_table(
        "drift_items",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("element", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column("first_analysis_id", sa.Uuid(), nullable=False),
        sa.Column("last_analysis_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("artifacts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "classification IN ('confirmed', 'potential', 'not_comparable', 'unknown')",
            name=op.f("ck_drift_items_classification"),
        ),
        sa.CheckConstraint("element IN ('node', 'connection', 'scope')", name=op.f("ck_drift_items_element")),
        sa.CheckConstraint("jsonb_typeof(artifacts) = 'array'", name=op.f("ck_drift_items_artifacts_array")),
        sa.CheckConstraint(
            "jsonb_typeof(history) = 'array' AND jsonb_array_length(history) >= 1",
            name=op.f("ck_drift_items_history_array"),
        ),
        sa.CheckConstraint("jsonb_typeof(links) = 'array'", name=op.f("ck_drift_items_links_array")),
        sa.CheckConstraint("key ~ '^dfi_[0-9a-f]{20}$'", name=op.f("ck_drift_items_key_format")),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'investigating', 'accepted', 'dismissed', 'resolved', 'reopened')",
            name=op.f("ck_drift_items_status"),
        ),
        sa.CheckConstraint(
            "type IN ('component_added', 'component_removed', 'component_modified', 'connection_added', 'connection_removed', 'connection_modified', 'configuration_changed', 'resource_changed', 'mapping_changed', 'unresolved_difference', 'coverage_changed', 'comparison_incompatible')",
            name=op.f("ck_drift_items_type"),
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_drift_items_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["first_analysis_id", "project_id"],
            ["drift_analyses.id", "drift_analyses.project_id"],
            name="fk_drift_items_first_analysis",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_analysis_id", "project_id"],
            ["drift_analyses.id", "drift_analyses.project_id"],
            name="fk_drift_items_last_analysis",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drift_items")),
        sa.UniqueConstraint("architecture_id", "key", name=op.f("uq_drift_items_architecture_id_key")),
    )
    op.create_index(
        "ix_drift_items_listing",
        "drift_items",
        ["project_id", "architecture_id", "status", "id"],
        unique=False,
    )
    # ### end Alembic commands ###
    _create_guards()


def downgrade() -> None:
    _drop_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_drift_items_listing", table_name="drift_items")
    op.drop_table("drift_items")
    op.drop_index("ix_drift_analyses_project_listing", table_name="drift_analyses")
    op.drop_index("ix_drift_analyses_discovery_run", table_name="drift_analyses")
    op.drop_index("ix_drift_analyses_architecture", table_name="drift_analyses")
    op.drop_table("drift_analyses")
    op.drop_index("ix_drift_identity_mappings_architecture", table_name="drift_identity_mappings")
    op.drop_table("drift_identity_mappings")
    op.drop_constraint(op.f("uq_discovery_runs_id_project_id"), "discovery_runs", type_="unique")
    # ### end Alembic commands ###


APPEND_ONLY = ("drift_analyses", "drift_identity_mappings")


def _create_guards() -> None:
    # An analysis is the evidence a review rests on, a mapping what a person confirmed: rewriting
    # either would make the review meaningless. Any UPDATE, DELETE or TRUNCATE is an error (the
    # function is the one requirement sets use).
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()"
        )
    # An item keeps its identity and its review history: only its latest detection, status, links
    # and artifacts change, and events are only appended.
    # An item's identity: what it is a difference of, and when it was first found.
    op.execute(
        """
        CREATE FUNCTION drift_items_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP <> 'UPDATE' THEN
                RAISE EXCEPTION '% is kept: % is not allowed', TG_TABLE_NAME, TG_OP
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF (SELECT jsonb_object_agg(k, v) FROM jsonb_each(to_jsonb(NEW)) AS e(k, v) WHERE k IN ('id', 'project_id', 'architecture_id', 'key', 'element', 'subject', 'path', 'first_analysis_id', 'created_at'))
                IS DISTINCT FROM
               (SELECT jsonb_object_agg(k, v) FROM jsonb_each(to_jsonb(OLD)) AS e(k, v) WHERE k IN ('id', 'project_id', 'architecture_id', 'key', 'element', 'subject', 'path', 'first_analysis_id', 'created_at'))
            THEN
                RAISE EXCEPTION '%: the identity of an item never changes', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF jsonb_array_length(NEW.history) < jsonb_array_length(OLD.history)
               OR (SELECT coalesce(jsonb_agg(e ORDER BY i), '[]'::jsonb)
                   FROM jsonb_array_elements(NEW.history) WITH ORDINALITY AS h(e, i)
                   WHERE i <= jsonb_array_length(OLD.history)) IS DISTINCT FROM OLD.history
            THEN
                RAISE EXCEPTION '%: the review history of an item only grows', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER drift_items_guard BEFORE UPDATE OR DELETE ON drift_items "
        "FOR EACH ROW EXECUTE FUNCTION drift_items_guard()"
    )
    op.execute(
        "CREATE TRIGGER drift_items_no_truncate BEFORE TRUNCATE ON drift_items "
        "FOR EACH STATEMENT EXECUTE FUNCTION drift_items_guard()"
    )


def _drop_guards() -> None:
    op.execute("DROP TRIGGER drift_items_no_truncate ON drift_items")
    op.execute("DROP TRIGGER drift_items_guard ON drift_items")
    op.execute("DROP FUNCTION drift_items_guard()")
    for table in APPEND_ONLY:
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
