"""requirements

Adds requirements (current state, soft-deleted) and requirement_versions (append-only history,
guarded by a trigger like audit_logs). The two tables reference each other: a version belongs to
a requirement, and a requirement's current_version must exist as a version (deferred, so both are
inserted in one transaction). Rationale for each constraint lives in persistence/models/requirement.py.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 17:13:29.441404+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirements",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "structured_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(category) BETWEEN 1 AND 64 AND category ~ '^[a-z][a-z0-9_]*$'",
            name=op.f("ck_requirements_category_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(structured_data) = 'object'", name=op.f("ck_requirements_structured_data_object")
        ),
        sa.CheckConstraint(
            "priority IN ('critical', 'high', 'medium', 'low')", name=op.f("ck_requirements_priority")
        ),
        sa.CheckConstraint(
            "source <> 'ai' OR confidence IS NOT NULL", name=op.f("ck_requirements_ai_confidence")
        ),
        sa.CheckConstraint("source IN ('user', 'ai')", name=op.f("ck_requirements_source")),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'satisfied', 'invalid', 'deprecated')",
            name=op.f("ck_requirements_status"),
        ),
        sa.CheckConstraint(
            "type IN ('functional', 'non_functional', 'capacity', 'performance', 'availability', 'reliability', 'security', 'data', 'compliance', 'operational', 'cost')",
            name=op.f("ck_requirements_type"),
        ),
        sa.CheckConstraint(
            "char_length(statement) BETWEEN 1 AND 5000", name=op.f("ck_requirements_statement_length")
        ),
        sa.CheckConstraint("char_length(title) BETWEEN 1 AND 200", name=op.f("ck_requirements_title_length")),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1", name=op.f("ck_requirements_confidence_range")
        ),
        sa.CheckConstraint("current_version >= 1", name=op.f("ck_requirements_current_version_positive")),
        sa.CheckConstraint("number >= 1", name=op.f("ck_requirements_number_positive")),
        sa.CheckConstraint(
            "octet_length(structured_data::text) <= 16384", name=op.f("ck_requirements_structured_data_size")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_requirements_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirements_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirements")),
        sa.UniqueConstraint("project_id", "number", name=op.f("uq_requirements_project_id_number")),
    )
    op.create_index(
        "ix_requirements_project_id_created_at_id_live",
        "requirements",
        ["project_id", "created_at", "id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "requirement_versions",
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("priority", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "structured_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(category) BETWEEN 1 AND 64 AND category ~ '^[a-z][a-z0-9_]*$'",
            name=op.f("ck_requirement_versions_category_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(structured_data) = 'object'",
            name=op.f("ck_requirement_versions_structured_data_object"),
        ),
        sa.CheckConstraint(
            "priority IN ('critical', 'high', 'medium', 'low')", name=op.f("ck_requirement_versions_priority")
        ),
        sa.CheckConstraint(
            "source <> 'ai' OR confidence IS NOT NULL", name=op.f("ck_requirement_versions_ai_confidence")
        ),
        sa.CheckConstraint("source IN ('user', 'ai')", name=op.f("ck_requirement_versions_source")),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'satisfied', 'invalid', 'deprecated')",
            name=op.f("ck_requirement_versions_status"),
        ),
        sa.CheckConstraint(
            "type IN ('functional', 'non_functional', 'capacity', 'performance', 'availability', 'reliability', 'security', 'data', 'compliance', 'operational', 'cost')",
            name=op.f("ck_requirement_versions_type"),
        ),
        sa.CheckConstraint(
            "change_reason IS NULL OR char_length(change_reason) BETWEEN 1 AND 500",
            name=op.f("ck_requirement_versions_change_reason_length"),
        ),
        sa.CheckConstraint(
            "char_length(statement) BETWEEN 1 AND 5000", name=op.f("ck_requirement_versions_statement_length")
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 200", name=op.f("ck_requirement_versions_title_length")
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_requirement_versions_confidence_range"),
        ),
        sa.CheckConstraint(
            "octet_length(structured_data::text) <= 16384",
            name=op.f("ck_requirement_versions_structured_data_size"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_requirement_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_requirement_versions_requirement_id_requirements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_versions")),
        sa.UniqueConstraint(
            "requirement_id", "version", name=op.f("uq_requirement_versions_requirement_id_version")
        ),
    )
    op.create_foreign_key(
        "fk_requirements_current_version_requirement_versions",
        "requirements",
        "requirement_versions",
        ["id", "current_version"],
        ["requirement_id", "version"],
        deferrable=True,
        initially="DEFERRED",
    )
    _create_version_guard()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_version_guard()
    op.drop_constraint(
        "fk_requirements_current_version_requirement_versions", "requirements", type_="foreignkey"
    )
    op.drop_table("requirement_versions")
    op.drop_index(
        "ix_requirements_project_id_created_at_id_live",
        table_name="requirements",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("requirements")
    # ### end Alembic commands ###


def _create_version_guard() -> None:
    # History is immutable: requirement sets, architectures and validation results refer to
    # versions, so any UPDATE, DELETE or TRUNCATE is an error. As with audit_logs, production should
    # also grant the application role only INSERT and SELECT on this table.
    op.execute(
        """
        CREATE FUNCTION requirement_versions_reject_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'requirement_versions is append-only: % is not allowed', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER requirement_versions_append_only
        BEFORE UPDATE OR DELETE ON requirement_versions
        FOR EACH ROW EXECUTE FUNCTION requirement_versions_reject_change()
        """
    )
    op.execute(
        """
        CREATE TRIGGER requirement_versions_no_truncate
        BEFORE TRUNCATE ON requirement_versions
        FOR EACH STATEMENT EXECUTE FUNCTION requirement_versions_reject_change()
        """
    )


def _drop_version_guard() -> None:
    op.execute("DROP TRIGGER requirement_versions_no_truncate ON requirement_versions")
    op.execute("DROP TRIGGER requirement_versions_append_only ON requirement_versions")
    op.execute("DROP FUNCTION requirement_versions_reject_change()")
