"""knowledge

Project knowledge: sources (an uploaded document, or an ADR or requirement read as a snapshot), each
ingestion run, each indexed version with its document and passages (their location, the identifiers
they name and their terms, GIN-indexed for the retrieval prefilter). Every foreign key is same-project.
No vector, embedding or similarity score is stored.

Runs, versions, documents and passages are append-only. A source keeps its identity, is never deleted
(archived instead), never un-archived, and its version in force never goes back: triggers refuse
anything else, and truncation.

Downgrading removes the tables and every stored source, version, passage and run with them.

Revision ID: 0023
Revises: 0022
Create Date: 2026-10-02 15:02:00.586160+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0023"
down_revision: str | None = "0022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("record_id", sa.Uuid(), nullable=True),
        sa.Column("record_label", sa.Text(), nullable=True),
        sa.Column("record_version", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("lifecycle", sa.Text(), nullable=False),
        sa.Column("indexed_version", sa.Integer(), nullable=True),
        sa.Column("indexed_checksum", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_by_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(lifecycle = 'archived') = (archived_at IS NOT NULL)",
            name=op.f("ck_knowledge_sources_archived_at"),
        ),
        sa.CheckConstraint(
            "(type = 'requirement') = (record_version IS NOT NULL)",
            name=op.f("ck_knowledge_sources_record_version"),
        ),
        sa.CheckConstraint(
            "(type IN ('decision', 'requirement')) = (path IS NULL)",
            name=op.f("ck_knowledge_sources_path_when_upload"),
        ),
        sa.CheckConstraint(
            "(type IN ('decision', 'requirement')) = (record_id IS NOT NULL)",
            name=op.f("ck_knowledge_sources_record_when_record"),
        ),
        sa.CheckConstraint(
            "indexed_checksum IS NULL OR indexed_checksum ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_knowledge_sources_checksum_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(metadata) = 'object'", name=op.f("ck_knowledge_sources_metadata_object")
        ),
        sa.CheckConstraint(
            "lifecycle IN ('active', 'archived')", name=op.f("ck_knowledge_sources_lifecycle")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'indexed', 'failed', 'stale')",
            name=op.f("ck_knowledge_sources_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('indexed', 'stale') OR indexed_version IS NOT NULL",
            name=op.f("ck_knowledge_sources_indexed_has_version"),
        ),
        sa.CheckConstraint(
            "type IN ('markdown', 'text', 'decision', 'requirement')", name=op.f("ck_knowledge_sources_type")
        ),
        sa.CheckConstraint(
            "(indexed_version IS NULL) = (indexed_checksum IS NULL)",
            name=op.f("ck_knowledge_sources_indexed_complete"),
        ),
        sa.CheckConstraint(
            "(record_id IS NULL) = (record_label IS NULL)", name=op.f("ck_knowledge_sources_record_label")
        ),
        sa.CheckConstraint(
            "char_length(name) BETWEEN 1 AND 200", name=op.f("ck_knowledge_sources_name_length")
        ),
        sa.CheckConstraint(
            "indexed_version IS NULL OR indexed_version >= 1",
            name=op.f("ck_knowledge_sources_indexed_version_positive"),
        ),
        sa.CheckConstraint(
            "path IS NULL OR char_length(path) BETWEEN 1 AND 256",
            name=op.f("ck_knowledge_sources_path_length"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_knowledge_sources_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_sources")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_knowledge_sources_id_project_id")),
    )
    op.create_index(
        "ix_knowledge_sources_listing", "knowledge_sources", ["project_id", "lifecycle", "id"], unique=False
    )
    op.create_index(
        "uq_knowledge_sources_active_path",
        "knowledge_sources",
        ["project_id", "path"],
        unique=True,
        postgresql_where=sa.text("lifecycle = 'active' AND path IS NOT NULL"),
    )
    op.create_index(
        "uq_knowledge_sources_active_record",
        "knowledge_sources",
        ["project_id", "record_id"],
        unique=True,
        postgresql_where=sa.text("lifecycle = 'active' AND record_id IS NOT NULL"),
    )
    op.create_table(
        "knowledge_ingestion_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("checksum", sa.Text(), nullable=True),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("indexed_version", sa.Integer(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retry_of", sa.Uuid(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'failed') = (jsonb_array_length(errors) > 0)",
            name=op.f("ck_knowledge_ingestion_runs_errors_when_failed"),
        ),
        sa.CheckConstraint(
            "(status IN ('completed', 'completed_with_warnings')) = (indexed_version IS NOT NULL)",
            name=op.f("ck_knowledge_ingestion_runs_indexed_when_completed"),
        ),
        sa.CheckConstraint(
            "checksum IS NULL OR checksum ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_knowledge_ingestion_runs_checksum_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(counts) = 'object'", name=op.f("ck_knowledge_ingestion_runs_counts_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(errors) = 'array'", name=op.f("ck_knowledge_ingestion_runs_errors_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(versions) = 'object'", name=op.f("ck_knowledge_ingestion_runs_versions_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(warnings) = 'array'", name=op.f("ck_knowledge_ingestion_runs_warnings_array")
        ),
        sa.CheckConstraint(
            "stage IN ('validating', 'extracting', 'normalizing', 'chunking', 'indexing', 'done')",
            name=op.f("ck_knowledge_ingestion_runs_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'completed_with_warnings', 'unchanged', 'failed')",
            name=op.f("ck_knowledge_ingestion_runs_ended"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'completed_with_warnings', 'unchanged', 'failed')",
            name=op.f("ck_knowledge_ingestion_runs_status"),
        ),
        sa.CheckConstraint(
            "trigger IN ('register', 'reindex')", name=op.f("ck_knowledge_ingestion_runs_trigger")
        ),
        sa.ForeignKeyConstraint(
            ["retry_of", "project_id"],
            ["knowledge_ingestion_runs.id", "knowledge_ingestion_runs.project_id"],
            name="fk_knowledge_ingestion_runs_retry_of",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "project_id"],
            ["knowledge_sources.id", "knowledge_sources.project_id"],
            name="fk_knowledge_ingestion_runs_sources",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_ingestion_runs")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_knowledge_ingestion_runs_id_project_id")),
    )
    op.create_index(
        "ix_knowledge_ingestion_runs_source",
        "knowledge_ingestion_runs",
        ["project_id", "source_id", "id"],
        unique=False,
    )
    op.create_table(
        "knowledge_source_versions",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("checksum", sa.Text(), nullable=False),
        sa.Column("ingestion_run_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("documents", sa.Integer(), nullable=False),
        sa.Column("chunks", sa.Integer(), nullable=False),
        sa.Column("versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("record", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "checksum ~ '^[0-9a-f]{64}$'", name=op.f("ck_knowledge_source_versions_checksum_format")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(versions) = 'object'", name=op.f("ck_knowledge_source_versions_versions_object")
        ),
        sa.CheckConstraint(
            "documents >= 1 AND chunks >= 0", name=op.f("ck_knowledge_source_versions_counts")
        ),
        sa.CheckConstraint("number >= 1", name=op.f("ck_knowledge_source_versions_number_positive")),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id", "project_id"],
            ["knowledge_ingestion_runs.id", "knowledge_ingestion_runs.project_id"],
            name="fk_knowledge_source_versions_runs",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "project_id"],
            ["knowledge_sources.id", "knowledge_sources.project_id"],
            name="fk_knowledge_source_versions_sources",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("source_id", "number", name=op.f("pk_knowledge_source_versions")),
    )
    op.create_index(
        "ix_knowledge_source_versions_project", "knowledge_source_versions", ["project_id"], unique=False
    )
    op.create_table(
        "knowledge_chunks",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("strategy", sa.Text(), nullable=False),
        sa.Column("occurrence", sa.Integer(), nullable=False),
        sa.Column("identifiers", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("terms", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(locator) = 'object'", name=op.f("ck_knowledge_chunks_locator_object")
        ),
        sa.CheckConstraint(
            "char_length(text) BETWEEN 1 AND 4000", name=op.f("ck_knowledge_chunks_text_length")
        ),
        sa.CheckConstraint("sequence >= 0 AND occurrence >= 0", name=op.f("ck_knowledge_chunks_order")),
        sa.ForeignKeyConstraint(
            ["source_id", "project_id"],
            ["knowledge_sources.id", "knowledge_sources.project_id"],
            name="fk_knowledge_chunks_sources",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "source_version"],
            ["knowledge_source_versions.source_id", "knowledge_source_versions.number"],
            name="fk_knowledge_chunks_versions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("source_id", "source_version", "chunk_id", name=op.f("pk_knowledge_chunks")),
        sa.UniqueConstraint(
            "source_id",
            "source_version",
            "sequence",
            name=op.f("uq_knowledge_chunks_source_id_source_version_sequence"),
        ),
    )
    op.create_index(
        "ix_knowledge_chunks_identifiers",
        "knowledge_chunks",
        ["identifiers"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("ix_knowledge_chunks_project", "knowledge_chunks", ["project_id"], unique=False)
    op.create_index(
        "ix_knowledge_chunks_terms", "knowledge_chunks", ["terms"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "knowledge_documents",
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("checksum", sa.Text(), nullable=False),
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("verification", sa.Text(), nullable=False),
        sa.Column("record_status", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "checksum ~ '^[0-9a-f]{64}$'", name=op.f("ck_knowledge_documents_checksum_format")
        ),
        sa.CheckConstraint(
            "content_type IN ('text/markdown', 'text/plain', 'application/vnd.architectos.record+json')",
            name=op.f("ck_knowledge_documents_content_type"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(metadata) = 'object'", name=op.f("ck_knowledge_documents_metadata_object")
        ),
        sa.CheckConstraint(
            "verification IN ('observed', 'user_provided', 'inferred', 'estimated', 'unknown', 'unsupported')",
            name=op.f("ck_knowledge_documents_verification"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "project_id"],
            ["knowledge_sources.id", "knowledge_sources.project_id"],
            name="fk_knowledge_documents_sources",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id", "source_version"],
            ["knowledge_source_versions.source_id", "knowledge_source_versions.number"],
            name="fk_knowledge_documents_versions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("source_id", "source_version", name=op.f("pk_knowledge_documents")),
    )
    # ### end Alembic commands ###
    _create_guards()


def downgrade() -> None:
    _drop_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("knowledge_documents")
    op.drop_index("ix_knowledge_chunks_terms", table_name="knowledge_chunks", postgresql_using="gin")
    op.drop_index("ix_knowledge_chunks_project", table_name="knowledge_chunks")
    op.drop_index("ix_knowledge_chunks_identifiers", table_name="knowledge_chunks", postgresql_using="gin")
    op.drop_table("knowledge_chunks")
    op.drop_index("ix_knowledge_source_versions_project", table_name="knowledge_source_versions")
    op.drop_table("knowledge_source_versions")
    op.drop_index("ix_knowledge_ingestion_runs_source", table_name="knowledge_ingestion_runs")
    op.drop_table("knowledge_ingestion_runs")
    op.drop_index(
        "uq_knowledge_sources_active_record",
        table_name="knowledge_sources",
        postgresql_where=sa.text("lifecycle = 'active' AND record_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_knowledge_sources_active_path",
        table_name="knowledge_sources",
        postgresql_where=sa.text("lifecycle = 'active' AND path IS NOT NULL"),
    )
    op.drop_index("ix_knowledge_sources_listing", table_name="knowledge_sources")
    op.drop_table("knowledge_sources")
    # ### end Alembic commands ###


APPEND_ONLY = (
    "knowledge_ingestion_runs",
    "knowledge_source_versions",
    "knowledge_documents",
    "knowledge_chunks",
)


def _create_guards() -> None:
    # What a passage says, where it is and which reading produced it is the evidence a citation rests
    # on: rewriting it would make every citation unexplainable. Any UPDATE, DELETE or TRUNCATE is an
    # error (the function is the one requirement sets use).
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()"
        )
    # A source keeps what it is (project, type, path or record, who registered it, when): only its index
    # state, version in force, record version read and lifecycle change; the version in force never
    # goes back; an archived source stays archived; nothing is deleted.
    op.execute(
        """
        CREATE FUNCTION knowledge_sources_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP <> 'UPDATE' THEN
                RAISE EXCEPTION '% is kept: % is not allowed', TG_TABLE_NAME, TG_OP
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF (NEW.id, NEW.project_id, NEW.type, NEW.path, NEW.record_id, NEW.record_label,
                NEW.created_by_user_id, NEW.created_at)
               IS DISTINCT FROM
               (OLD.id, OLD.project_id, OLD.type, OLD.path, OLD.record_id, OLD.record_label,
                OLD.created_by_user_id, OLD.created_at)
            THEN
                RAISE EXCEPTION '%: the identity of a source never changes', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF OLD.indexed_version IS NOT NULL
               AND (NEW.indexed_version IS NULL OR NEW.indexed_version < OLD.indexed_version)
            THEN
                RAISE EXCEPTION '%: the version in force never goes back', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF OLD.lifecycle = 'archived' AND NEW.lifecycle <> 'archived' THEN
                RAISE EXCEPTION '%: an archived source stays archived', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER knowledge_sources_guard BEFORE UPDATE OR DELETE ON knowledge_sources "
        "FOR EACH ROW EXECUTE FUNCTION knowledge_sources_guard()"
    )
    op.execute(
        "CREATE TRIGGER knowledge_sources_no_truncate BEFORE TRUNCATE ON knowledge_sources "
        "FOR EACH STATEMENT EXECUTE FUNCTION knowledge_sources_guard()"
    )


def _drop_guards() -> None:
    op.execute("DROP TRIGGER knowledge_sources_no_truncate ON knowledge_sources")
    op.execute("DROP TRIGGER knowledge_sources_guard ON knowledge_sources")
    op.execute("DROP FUNCTION knowledge_sources_guard()")
    for table in APPEND_ONLY:
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
