"""architecture diffs

An architecture diff records one comparison of two exact states of a project — each a revision
(same-project foreign keys to the architecture and the revision) or an architecture agent run's
candidate (a same-project foreign key to the run) — with each state's content hash (never a copy of
either architecture), the semantic diff with its groups, the requirement and decision impacts, the
engines' comparison, and who asked when. An explanation run records one AI explanation of a diff: the
model, prompt version and usage, the SHA-256 and size of the model's output (never the output, the
prompt or the retrieved text), the validated explanation or why there is none, and the citations of
the passages it cites.

Both tables are append-only (a trigger refuses UPDATE, DELETE and TRUNCATE): a diff is what was
compared, as it was, and asking again for an explanation adds a run. The agent runs gain a unique
(id, project_id), the target of the diffs' same-project foreign keys.

Downgrading removes both tables and every stored diff and explanation with them (no architecture,
revision, agent run or analysis is affected).

Revision ID: 0025
Revises: 0024
Create Date: 2026-10-03 11:41:42.923950+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0025"
down_revision: str | None = "0024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # first: the agent runs' (id, project_id) is what the diffs' same-project foreign keys reference
    op.create_unique_constraint(
        op.f("uq_architecture_agent_runs_id_project_id"), "architecture_agent_runs", ["id", "project_id"]
    )
    op.create_table(
        "architecture_diffs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("compared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("base_kind", sa.Text(), nullable=False),
        sa.Column("base_architecture_id", sa.Uuid(), nullable=True),
        sa.Column("base_revision_number", sa.Integer(), nullable=True),
        sa.Column("base_run_id", sa.Uuid(), nullable=True),
        sa.Column("base_content_hash", sa.Text(), nullable=False),
        sa.Column("base_label", sa.Text(), nullable=False),
        sa.Column("target_kind", sa.Text(), nullable=False),
        sa.Column("target_architecture_id", sa.Uuid(), nullable=True),
        sa.Column("target_revision_number", sa.Integer(), nullable=True),
        sa.Column("target_run_id", sa.Uuid(), nullable=True),
        sa.Column("target_content_hash", sa.Text(), nullable=False),
        sa.Column("target_label", sa.Text(), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("semantic", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_count", sa.Integer(), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("decisions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unknowns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(base_kind = 'revision' AND base_architecture_id IS NOT NULL AND base_revision_number IS NOT NULL AND base_run_id IS NULL) OR (base_kind = 'candidate' AND base_run_id IS NOT NULL AND base_architecture_id IS NULL AND base_revision_number IS NULL)",
            name=op.f("ck_architecture_diffs_base_reference"),
        ),
        sa.CheckConstraint(
            "(target_kind = 'revision' AND target_architecture_id IS NOT NULL AND target_revision_number IS NOT NULL AND target_run_id IS NULL) OR (target_kind = 'candidate' AND target_run_id IS NOT NULL AND target_architecture_id IS NULL AND target_revision_number IS NULL)",
            name=op.f("ck_architecture_diffs_target_reference"),
        ),
        sa.CheckConstraint(
            "base_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_architecture_diffs_base_content_hash_format"),
        ),
        sa.CheckConstraint(
            "base_kind IN ('revision', 'candidate')", name=op.f("ck_architecture_diffs_base_kind")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(counts) = 'object'", name=op.f("ck_architecture_diffs_counts_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(decisions) = 'array'", name=op.f("ck_architecture_diffs_decisions_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(engines) = 'array'", name=op.f("ck_architecture_diffs_engines_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(request) = 'object'", name=op.f("ck_architecture_diffs_request_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(requirements) = 'array'", name=op.f("ck_architecture_diffs_requirements_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(semantic) = 'object'", name=op.f("ck_architecture_diffs_semantic_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(unknowns) = 'array'", name=op.f("ck_architecture_diffs_unknowns_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(warnings) = 'array'", name=op.f("ck_architecture_diffs_warnings_array")
        ),
        sa.CheckConstraint(
            "target_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_architecture_diffs_target_content_hash_format"),
        ),
        sa.CheckConstraint(
            "target_kind IN ('revision', 'candidate')", name=op.f("ck_architecture_diffs_target_kind")
        ),
        sa.CheckConstraint("change_count >= 0", name=op.f("ck_architecture_diffs_change_count_non_negative")),
        sa.CheckConstraint(
            "char_length(base_label) BETWEEN 1 AND 200", name=op.f("ck_architecture_diffs_base_label_length")
        ),
        sa.CheckConstraint(
            "char_length(target_label) BETWEEN 1 AND 200",
            name=op.f("ck_architecture_diffs_target_label_length"),
        ),
        sa.CheckConstraint(
            "octet_length(semantic::text || requirements::text || decisions::text || engines::text) <= 16777216",
            name=op.f("ck_architecture_diffs_parts_size"),
        ),
        sa.ForeignKeyConstraint(
            ["base_architecture_id", "base_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_architecture_diffs_base_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["base_architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_architecture_diffs_base_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["base_run_id", "project_id"],
            ["architecture_agent_runs.id", "architecture_agent_runs.project_id"],
            name="fk_architecture_diffs_base_agent_runs",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_architecture_diffs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_architecture_diffs_target_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_architecture_id", "target_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_architecture_diffs_target_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_run_id", "project_id"],
            ["architecture_agent_runs.id", "architecture_agent_runs.project_id"],
            name="fk_architecture_diffs_target_agent_runs",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_architecture_diffs")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_architecture_diffs_id_project_id")),
    )
    op.create_index(
        "ix_architecture_diffs_base_revision",
        "architecture_diffs",
        ["base_architecture_id", "base_revision_number"],
        unique=False,
    )
    op.create_index("ix_architecture_diffs_base_run", "architecture_diffs", ["base_run_id"], unique=False)
    op.create_index(
        "ix_architecture_diffs_project_listing",
        "architecture_diffs",
        ["project_id", "compared_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_architecture_diffs_target_revision",
        "architecture_diffs",
        ["target_architecture_id", "target_revision_number"],
        unique=False,
    )
    op.create_index("ix_architecture_diffs_target_run", "architecture_diffs", ["target_run_id"], unique=False)
    op.create_table(
        "architecture_diff_explanations",
        sa.Column("diff_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_output_sha256", sa.Text(), nullable=True),
        sa.Column("raw_output_bytes", sa.Integer(), nullable=True),
        sa.Column("explanation", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("failure", sa.Text(), nullable=True),
        sa.Column("rejections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'completed') = (explanation IS NOT NULL)",
            name=op.f("ck_architecture_diff_explanations_explanation_when_completed"),
        ),
        sa.CheckConstraint(
            "(status = 'failed') = (failure IS NOT NULL)",
            name=op.f("ck_architecture_diff_explanations_failure_when_failed"),
        ),
        sa.CheckConstraint(
            "explanation IS NULL OR jsonb_typeof(explanation) = 'object'",
            name=op.f("ck_architecture_diff_explanations_explanation_object"),
        ),
        sa.CheckConstraint(
            "failure IS NULL OR failure IN ('llm_unavailable', 'llm_timeout', 'llm_malformed_output', 'explanation_rejected', 'budget_exhausted')",
            name=op.f("ck_architecture_diff_explanations_failure"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(evidence) = 'array'", name=op.f("ck_architecture_diff_explanations_evidence_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(limitations) = 'array'",
            name=op.f("ck_architecture_diff_explanations_limitations_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(rejections) = 'array'",
            name=op.f("ck_architecture_diff_explanations_rejections_array"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(usage) = 'object'", name=op.f("ck_architecture_diff_explanations_usage_object")
        ),
        sa.CheckConstraint(
            "octet_length(coalesce(explanation::text, '')) <= 1048576",
            name=op.f("ck_architecture_diff_explanations_explanation_size"),
        ),
        sa.CheckConstraint(
            "raw_output_sha256 IS NULL OR (raw_output_sha256 ~ '^[0-9a-f]{64}$' AND raw_output_bytes >= 0)",
            name=op.f("ck_architecture_diff_explanations_raw_output_format"),
        ),
        sa.CheckConstraint(
            "status <> 'not_needed' OR (model IS NULL AND raw_output_sha256 IS NULL)",
            name=op.f("ck_architecture_diff_explanations_no_model_when_not_needed"),
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'failed', 'not_needed')",
            name=op.f("ck_architecture_diff_explanations_status"),
        ),
        sa.CheckConstraint(
            "(raw_output_sha256 IS NULL) = (raw_output_bytes IS NULL)",
            name=op.f("ck_architecture_diff_explanations_raw_output_complete"),
        ),
        sa.CheckConstraint(
            "model IS NULL OR char_length(model) BETWEEN 1 AND 128",
            name=op.f("ck_architecture_diff_explanations_model_length"),
        ),
        sa.CheckConstraint(
            "prompt_version IS NULL OR char_length(prompt_version) BETWEEN 1 AND 64",
            name=op.f("ck_architecture_diff_explanations_prompt_version_length"),
        ),
        sa.ForeignKeyConstraint(
            ["diff_id", "project_id"],
            ["architecture_diffs.id", "architecture_diffs.project_id"],
            name="fk_architecture_diff_explanations_diffs",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_architecture_diff_explanations")),
    )
    op.create_index(
        "ix_architecture_diff_explanations_diff",
        "architecture_diff_explanations",
        ["diff_id", "project_id", "requested_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###
    _create_append_only_guards()


def downgrade() -> None:
    _drop_append_only_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_architecture_diff_explanations_diff", table_name="architecture_diff_explanations")
    op.drop_table("architecture_diff_explanations")
    op.drop_index("ix_architecture_diffs_target_run", table_name="architecture_diffs")
    op.drop_index("ix_architecture_diffs_target_revision", table_name="architecture_diffs")
    op.drop_index("ix_architecture_diffs_project_listing", table_name="architecture_diffs")
    op.drop_index("ix_architecture_diffs_base_run", table_name="architecture_diffs")
    op.drop_index("ix_architecture_diffs_base_revision", table_name="architecture_diffs")
    op.drop_table("architecture_diffs")
    op.drop_constraint(
        op.f("uq_architecture_agent_runs_id_project_id"), "architecture_agent_runs", type_="unique"
    )
    # ### end Alembic commands ###


_GUARDED = ("architecture_diffs", "architecture_diff_explanations")


def _create_append_only_guards() -> None:
    # A diff is what a person compared and may have acted on: rewriting it, or an explanation of it,
    # would make the record unexplainable. Any UPDATE, DELETE or TRUNCATE is an error.
    op.execute(
        """
        CREATE FUNCTION architecture_diffs_reject_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
        """
    )
    for table in _GUARDED:
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION architecture_diffs_reject_change()
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER {table}_no_truncate
            BEFORE TRUNCATE ON {table}
            FOR EACH STATEMENT EXECUTE FUNCTION architecture_diffs_reject_change()
            """
        )


def _drop_append_only_guards() -> None:
    for table in _GUARDED:
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    op.execute("DROP FUNCTION architecture_diffs_reject_change()")
