"""security analyses

A security analysis records one execution of the deterministic security engine against one
architecture revision: the request's inputs (scope, analyzers, assumptions), the project's policy as
it was, and the in-force requirements it read (id, version, status); the analyzer set, fingerprints,
summary, trust zones, requirement and policy checks, what could not run, and limitations. Components
and findings are rows of their own, for paging and filtering; findings keep their canonical position
and stable id, and a finding's type fixes its category and basis. No secret is stored: findings carry
element ids, closed-set values and the names of secret-looking settings, never their values.

The three tables are append-only (triggers, with the guard function of requirement sets, 0004): an
analysis is stored once, finished. Analyses reference their architecture and revision, and rows
their analysis, through same-project foreign keys.

Downgrading removes the three tables and every stored security analysis with them.

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-27 04:31:49.543544+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

TABLES = ("security_analyses", "security_components", "security_findings")

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_analyses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("revision_content_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("analyzer_set", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context_fingerprint", sa.Text(), nullable=True),
        sa.Column("result_fingerprint", sa.Text(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("trust_zones", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unsupported", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(checks) = 'array'", name=op.f("ck_security_analyses_checks_array")),
        sa.CheckConstraint(
            "jsonb_typeof(inputs) = 'object'", name=op.f("ck_security_analyses_inputs_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(trust_zones) = 'array'", name=op.f("ck_security_analyses_trust_zones_array")
        ),
        sa.CheckConstraint(
            "revision_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_security_analyses_revision_content_hash_format"),
        ),
        sa.CheckConstraint(
            "status <> 'failed' OR (completed_at IS NOT NULL AND error_code IS NOT NULL)",
            name=op.f("ck_security_analyses_failed_has_error"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'partial', 'insufficient_input', 'unsupported', 'failed')",
            name=op.f("ck_security_analyses_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'failed') OR (completed_at IS NOT NULL AND result_fingerprint IS NOT NULL AND summary IS NOT NULL AND analyzer_set IS NOT NULL)",
            name=op.f("ck_security_analyses_finished_has_result"),
        ),
        sa.CheckConstraint(
            "label IS NULL OR char_length(label) BETWEEN 1 AND 100",
            name=op.f("ck_security_analyses_label_length"),
        ),
        sa.CheckConstraint(
            "revision_number >= 1", name=op.f("ck_security_analyses_revision_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_security_analyses_architecture_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_security_analyses_revision_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_analyses")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_security_analyses_id_project_id")),
    )
    op.create_index(
        op.f("ix_security_analyses_architecture_id_requested_at_id"),
        "security_analyses",
        ["architecture_id", "requested_at", "id"],
        unique=False,
    )
    op.create_table(
        "security_components",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("coverage", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "coverage IN ('modeled', 'partial', 'not_modeled')", name=op.f("ck_security_components_coverage")
        ),
        sa.CheckConstraint("jsonb_typeof(data) = 'object'", name=op.f("ck_security_components_data_object")),
        sa.ForeignKeyConstraint(
            ["analysis_id", "project_id"],
            ["security_analyses.id", "security_analyses.project_id"],
            name="fk_security_components_analysis_security_analyses",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_components")),
        sa.UniqueConstraint(
            "analysis_id", "node_id", name=op.f("uq_security_components_analysis_id_node_id")
        ),
    )
    op.create_table(
        "security_findings",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("certainty", sa.Text(), nullable=False),
        sa.Column("threat", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(type = 'authentication_not_modeled' AND category = 'authentication' AND basis = 'not_evaluable') OR (type = 'authorization_not_modeled' AND category = 'authorization' AND basis = 'not_evaluable') OR (type = 'crossing_controls_not_modeled' AND category = 'trust_boundary' AND basis = 'not_evaluable') OR (type = 'data_classification_not_modeled' AND category = 'data_protection' AND basis = 'not_evaluable') OR (type = 'encryption_not_modeled' AND category = 'encryption' AND basis = 'not_evaluable') OR (type = 'exposure_not_modeled' AND category = 'exposure' AND basis = 'not_evaluable') OR (type = 'hardcoded_secret' AND category = 'secrets' AND basis = 'control_gap') OR (type = 'inconsistent_authentication' AND category = 'authentication' AND basis = 'potential_risk') OR (type = 'inconsistent_trust_boundary' AND category = 'trust_boundary' AND basis = 'not_evaluable') OR (type = 'insufficient_flow_semantics' AND category = 'trust_boundary' AND basis = 'not_evaluable') OR (type = 'missing_authentication' AND category = 'authentication' AND basis = 'control_gap') OR (type = 'missing_authorization' AND category = 'authorization' AND basis = 'control_gap') OR (type = 'policy_not_evaluable' AND category = 'policy' AND basis = 'not_evaluable') OR (type = 'policy_violated' AND category = 'policy' AND basis = 'violation') OR (type = 'public_management_interface' AND category = 'exposure' AND basis = 'control_gap') OR (type = 'requirement_not_evaluable' AND category = 'requirement' AND basis = 'not_evaluable') OR (type = 'requirement_violated' AND category = 'requirement' AND basis = 'violation') OR (type = 'secret_in_configuration' AND category = 'secrets' AND basis = 'potential_risk') OR (type = 'secret_source_not_modeled' AND category = 'secrets' AND basis = 'not_evaluable') OR (type = 'sensitive_component_reachable_from_public' AND category = 'exposure' AND basis = 'potential_risk') OR (type = 'sensitive_data_crosses_boundary' AND category = 'trust_boundary' AND basis = 'potential_risk') OR (type = 'threat_candidate' AND category = 'threat' AND basis = 'potential_risk') OR (type = 'trust_level_not_modeled' AND category = 'trust_boundary' AND basis = 'not_evaluable') OR (type = 'unauthenticated_connection' AND category = 'authentication' AND basis = 'control_gap') OR (type = 'unencrypted_data_at_rest' AND category = 'encryption' AND basis = 'control_gap') OR (type = 'unencrypted_data_in_transit' AND category = 'encryption' AND basis = 'control_gap') OR (type = 'unprotected_boundary_crossing' AND category = 'trust_boundary' AND basis = 'control_gap')",
            name=op.f("ck_security_findings_type_fixes_category_and_basis"),
        ),
        sa.CheckConstraint(
            "(type = 'threat_candidate') = (threat IS NOT NULL) AND (threat IS NULL OR threat IN ('spoofing', 'tampering', 'repudiation', 'information_disclosure', 'denial_of_service', 'elevation_of_privilege'))",
            name=op.f("ck_security_findings_threat"),
        ),
        sa.CheckConstraint(
            "basis IN ('control_gap', 'potential_risk', 'violation', 'not_evaluable')",
            name=op.f("ck_security_findings_basis"),
        ),
        sa.CheckConstraint(
            "category IN ('trust_boundary', 'authentication', 'authorization', 'encryption', 'data_protection', 'secrets', 'exposure', 'threat', 'requirement', 'policy')",
            name=op.f("ck_security_findings_category"),
        ),
        sa.CheckConstraint(
            "certainty IN ('modeled', 'candidate')", name=op.f("ck_security_findings_certainty")
        ),
        sa.CheckConstraint(
            "finding_id ~ '^sec_[0-9a-f]{16}$'", name=op.f("ck_security_findings_finding_id_format")
        ),
        sa.CheckConstraint("jsonb_typeof(data) = 'object'", name=op.f("ck_security_findings_data_object")),
        sa.CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low', 'info')",
            name=op.f("ck_security_findings_severity"),
        ),
        sa.CheckConstraint(
            "type IN ('unprotected_boundary_crossing', 'crossing_controls_not_modeled', 'sensitive_data_crosses_boundary', 'trust_level_not_modeled', 'inconsistent_trust_boundary', 'insufficient_flow_semantics', 'missing_authentication', 'unauthenticated_connection', 'inconsistent_authentication', 'authentication_not_modeled', 'missing_authorization', 'authorization_not_modeled', 'unencrypted_data_at_rest', 'unencrypted_data_in_transit', 'encryption_not_modeled', 'data_classification_not_modeled', 'hardcoded_secret', 'secret_in_configuration', 'secret_source_not_modeled', 'public_management_interface', 'sensitive_component_reachable_from_public', 'exposure_not_modeled', 'threat_candidate', 'requirement_violated', 'requirement_not_evaluable', 'policy_violated', 'policy_not_evaluable')",
            name=op.f("ck_security_findings_type"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_security_findings_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["analysis_id", "project_id"],
            ["security_analyses.id", "security_analyses.project_id"],
            name="fk_security_findings_analysis_security_analyses",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_findings")),
        sa.UniqueConstraint(
            "analysis_id", "finding_id", name=op.f("uq_security_findings_analysis_id_finding_id")
        ),
        sa.UniqueConstraint(
            "analysis_id", "position", name=op.f("uq_security_findings_analysis_id_position")
        ),
    )
    # ### end Alembic commands ###
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()"
        )


def downgrade() -> None:
    for table in reversed(TABLES):
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("security_findings")
    op.drop_table("security_components")
    op.drop_index(
        op.f("ix_security_analyses_architecture_id_requested_at_id"), table_name="security_analyses"
    )
    op.drop_table("security_analyses")
    # ### end Alembic commands ###
