"""requirement sets

Adds requirement_sets (immutable, numbered snapshots with the stored Architecture Planning Input
and its content hash) and requirement_set_items (the pinned requirement versions). Both are
append-only, guarded by triggers like requirement_versions. Composite foreign keys make the
database guarantee that a set, its items and their requirements belong to one project.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 18:07:52.237054+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First: the items' same-project foreign key needs this target.
    op.create_unique_constraint(op.f("uq_requirements_id_project_id"), "requirements", ["id", "project_id"])
    op.create_table(
        "requirement_sets",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), server_default="", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("planning_input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("requirement_count", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_requirement_sets_content_hash_format")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(planning_input) = 'object'", name=op.f("ck_requirement_sets_planning_input_object")
        ),
        sa.CheckConstraint(
            "char_length(description) <= 2000", name=op.f("ck_requirement_sets_description_length")
        ),
        sa.CheckConstraint("char_length(name) <= 100", name=op.f("ck_requirement_sets_name_length")),
        sa.CheckConstraint("number >= 1", name=op.f("ck_requirement_sets_number_positive")),
        sa.CheckConstraint(
            "octet_length(planning_input::text) <= 16777216",
            name=op.f("ck_requirement_sets_planning_input_size"),
        ),
        sa.CheckConstraint(
            "requirement_count >= 1", name=op.f("ck_requirement_sets_requirement_count_positive")
        ),
        sa.CheckConstraint("schema_version >= 1", name=op.f("ck_requirement_sets_schema_version_positive")),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirement_sets_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_sets")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_requirement_sets_id_project_id")),
        sa.UniqueConstraint("project_id", "number", name=op.f("uq_requirement_sets_project_id_number")),
    )
    op.create_table(
        "requirement_set_items",
        sa.Column("requirement_set_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_requirement_set_items_version_positive")),
        sa.ForeignKeyConstraint(
            ["requirement_id", "project_id"],
            ["requirements.id", "requirements.project_id"],
            name="fk_requirement_set_items_requirement_requirements",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id", "version"],
            ["requirement_versions.requirement_id", "requirement_versions.version"],
            name="fk_requirement_set_items_version_requirement_versions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_set_id", "project_id"],
            ["requirement_sets.id", "requirement_sets.project_id"],
            name="fk_requirement_set_items_set_requirement_sets",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "requirement_set_id", "requirement_id", name=op.f("pk_requirement_set_items")
        ),
    )
    op.create_index(
        op.f("ix_requirement_set_items_requirement_id_version"),
        "requirement_set_items",
        ["requirement_id", "version"],
        unique=False,
    )
    _create_append_only_guards()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_append_only_guards()
    op.drop_index(op.f("ix_requirement_set_items_requirement_id_version"), table_name="requirement_set_items")
    op.drop_table("requirement_set_items")
    op.drop_table("requirement_sets")
    op.drop_constraint(op.f("uq_requirements_id_project_id"), "requirements", type_="unique")
    # ### end Alembic commands ###


_GUARDED = ("requirement_sets", "requirement_set_items")


def _create_append_only_guards() -> None:
    # A set is what an architecture was planned against: rewriting it would make results
    # unexplainable. Any UPDATE, DELETE or TRUNCATE is an error.
    op.execute(
        """
        CREATE FUNCTION requirement_sets_reject_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
        """
    )
    for table in _GUARDED:
        op.execute(
            f"""
            CREATE TRIGGER {table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()
            """
        )
        op.execute(
            f"""
            CREATE TRIGGER {table}_no_truncate
            BEFORE TRUNCATE ON {table}
            FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()
            """
        )


def _drop_append_only_guards() -> None:
    for table in _GUARDED:
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    op.execute("DROP FUNCTION requirement_sets_reject_change()")
