"""simulations

A simulation records one scenario evaluated against one architecture revision by the deterministic
simulation engine: the request's inputs (the scenario snapshot, the analyses asked, the workload,
entries, pricing inputs and assumptions), the requirements read (id, version, status), the project's
provider and currency, the overlay evaluated (to reconstruct it), the engine and model versions,
the fingerprints, the summary, the runs of each engine, the entry impacts, the assumptions, the
calculation trace, what could not be established and the limitations. Component outcomes and deltas
are rows of their own, for paging and filtering; deltas keep their canonical position. Nothing here
is a measurement, and the architecture itself is never copied.

The three tables are append-only (triggers, with the guard function of requirement sets, 0004): a
simulation is stored once, finished. Simulations reference their architecture and revision, and rows
their simulation, through same-project foreign keys.

Downgrading removes the three tables and every stored simulation with them.

Revision ID: 0018
Revises: 0017
Create Date: 2026-09-27 15:36:40.878430+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

TABLES = ("simulations", "simulation_components", "simulation_deltas")

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("revision_content_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overlay", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("engine_set", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context_fingerprint", sa.Text(), nullable=True),
        sa.Column("scenario_fingerprint", sa.Text(), nullable=True),
        sa.Column("result_fingerprint", sa.Text(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("runs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("entries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unsupported", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("jsonb_typeof(entries) = 'array'", name=op.f("ck_simulations_entries_array")),
        sa.CheckConstraint("jsonb_typeof(inputs) = 'object'", name=op.f("ck_simulations_inputs_object")),
        sa.CheckConstraint("jsonb_typeof(runs) = 'array'", name=op.f("ck_simulations_runs_array")),
        sa.CheckConstraint(
            "revision_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_simulations_revision_content_hash_format"),
        ),
        sa.CheckConstraint(
            "status <> 'failed' OR (completed_at IS NOT NULL AND error_code IS NOT NULL)",
            name=op.f("ck_simulations_failed_has_error"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'partial', 'unsupported', 'failed')",
            name=op.f("ck_simulations_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'failed') OR (completed_at IS NOT NULL AND result_fingerprint IS NOT NULL AND summary IS NOT NULL AND engine_set IS NOT NULL AND overlay IS NOT NULL)",
            name=op.f("ck_simulations_finished_has_result"),
        ),
        sa.CheckConstraint(
            "label IS NULL OR char_length(label) BETWEEN 1 AND 100", name=op.f("ck_simulations_label_length")
        ),
        sa.CheckConstraint("revision_number >= 1", name=op.f("ck_simulations_revision_number_positive")),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_simulations_architecture_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_simulations_revision_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulations")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_simulations_id_project_id")),
    )
    op.create_index(
        op.f("ix_simulations_architecture_id_requested_at_id"),
        "simulations",
        ["architecture_id", "requested_at", "id"],
        unique=False,
    )
    op.create_table(
        "simulation_components",
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("unavailable", sa.Boolean(), nullable=False),
        sa.Column("impact", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "impact IS NULL OR impact IN ('unaffected', 'tolerated', 'degraded', 'interrupted', 'unknown')",
            name=op.f("ck_simulation_components_impact"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(data) = 'object'", name=op.f("ck_simulation_components_data_object")
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id", "project_id"],
            ["simulations.id", "simulations.project_id"],
            name="fk_simulation_components_simulation_simulations",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_components")),
        sa.UniqueConstraint(
            "simulation_id", "node_id", name=op.f("uq_simulation_components_simulation_id_node_id")
        ),
    )
    op.create_table(
        "simulation_deltas",
        sa.Column("simulation_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("analysis", sa.Text(), nullable=False),
        sa.Column("element_id", sa.Text(), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("comparable", sa.Boolean(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "analysis IN ('capacity', 'reliability', 'cost')", name=op.f("ck_simulation_deltas_analysis")
        ),
        sa.CheckConstraint("jsonb_typeof(data) = 'object'", name=op.f("ck_simulation_deltas_data_object")),
        sa.CheckConstraint("position >= 0", name=op.f("ck_simulation_deltas_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["simulation_id", "project_id"],
            ["simulations.id", "simulations.project_id"],
            name="fk_simulation_deltas_simulation_simulations",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_deltas")),
        sa.UniqueConstraint(
            "simulation_id",
            "analysis",
            "element_id",
            "metric",
            name=op.f("uq_simulation_deltas_simulation_id_analysis_element_id_metric"),
        ),
        sa.UniqueConstraint(
            "simulation_id", "position", name=op.f("uq_simulation_deltas_simulation_id_position")
        ),
    )
    # ### end Alembic commands ###
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()"
        )


def downgrade() -> None:
    for table in reversed(TABLES):
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simulation_deltas")
    op.drop_table("simulation_components")
    op.drop_index(op.f("ix_simulations_architecture_id_requested_at_id"), table_name="simulations")
    op.drop_table("simulations")
    # ### end Alembic commands ###
