"""architecture agent runs

An agent run records one run of the architecture agent: what a person asked (a requirement set and
an optional base revision, both referenced by same-project foreign keys; the request and its budget),
who and when, where it stands, what it used, its questions and answers, the validated proposal, the
candidate architecture with the engines' reports — or why it failed — and the person's decision: the
revision it became (same-project foreign keys) or why it was rejected. Never stored: prompts, context,
retrieved text or the model's raw output (only that output's SHA-256 and size).

A trigger keeps the record honest: a run's request never changes; a finished run (failed, cancelled,
accepted, rejected) never changes; a candidate, once stored, is the one reviewed; an accepted run is
not deleted (it is the provenance of its revision); the table is not truncated.

Downgrading removes the table and every stored agent run with it (the revisions accepted from them
are kept: they are ordinary revisions with source ``ai``).

Revision ID: 0024
Revises: 0023
Create Date: 2026-10-02 18:53:33.815522+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0024"
down_revision: str | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "architecture_agent_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requirement_set_id", sa.Uuid(), nullable=False),
        sa.Column("base_architecture_id", sa.Uuid(), nullable=True),
        sa.Column("base_revision_number", sa.Integer(), nullable=True),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposal", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("rejections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidate", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("candidate_content_hash", sa.Text(), nullable=True),
        sa.Column("reports", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_output_sha256", sa.Text(), nullable=True),
        sa.Column("raw_output_bytes", sa.Integer(), nullable=True),
        sa.Column("failure", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("accepted_architecture_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_revision_number", sa.Integer(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'accepted') = (accepted_architecture_id IS NOT NULL AND accepted_revision_number IS NOT NULL)",
            name=op.f("ck_architecture_agent_runs_revision_when_accepted"),
        ),
        sa.CheckConstraint(
            "(status = 'failed') = (failure IS NOT NULL)",
            name=op.f("ck_architecture_agent_runs_failure_when_failed"),
        ),
        sa.CheckConstraint(
            "(status = 'rejected') = (decision_reason IS NOT NULL)",
            name=op.f("ck_architecture_agent_runs_reason_when_rejected"),
        ),
        sa.CheckConstraint(
            "(status IN ('candidate_ready', 'accepted', 'rejected')) = (candidate IS NOT NULL AND candidate_content_hash IS NOT NULL)",
            name=op.f("ck_architecture_agent_runs_candidate_when_ready"),
        ),
        sa.CheckConstraint(
            "candidate IS NULL OR jsonb_typeof(candidate) = 'object'",
            name=op.f("ck_architecture_agent_runs_candidate_object"),
        ),
        sa.CheckConstraint(
            "candidate_content_hash IS NULL OR candidate_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_architecture_agent_runs_candidate_hash_format"),
        ),
        sa.CheckConstraint(
            "failure IS NULL OR jsonb_typeof(failure) = 'object'",
            name=op.f("ck_architecture_agent_runs_failure_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(answers) = 'array'", name=op.f("ck_architecture_agent_runs_answers_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(budget) = 'object'", name=op.f("ck_architecture_agent_runs_budget_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(history) = 'array'", name=op.f("ck_architecture_agent_runs_history_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(limitations) = 'array'", name=op.f("ck_architecture_agent_runs_limitations_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(questions) = 'array'", name=op.f("ck_architecture_agent_runs_questions_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(rejections) = 'array'", name=op.f("ck_architecture_agent_runs_rejections_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(reports) = 'array'", name=op.f("ck_architecture_agent_runs_reports_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(request) = 'object'", name=op.f("ck_architecture_agent_runs_request_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(usage) = 'object'", name=op.f("ck_architecture_agent_runs_usage_object")
        ),
        sa.CheckConstraint(
            "octet_length(coalesce(proposal::text, '') || coalesce(candidate::text, '') || reports::text) <= 8388608",
            name=op.f("ck_architecture_agent_runs_parts_size"),
        ),
        sa.CheckConstraint(
            "proposal IS NULL OR jsonb_typeof(proposal) = 'object'",
            name=op.f("ck_architecture_agent_runs_proposal_object"),
        ),
        sa.CheckConstraint(
            "raw_output_sha256 IS NULL OR (raw_output_sha256 ~ '^[0-9a-f]{64}$' AND raw_output_bytes >= 0)",
            name=op.f("ck_architecture_agent_runs_raw_output_format"),
        ),
        sa.CheckConstraint(
            "stage IN ('intake', 'interpretation', 'retrieval', 'context', 'proposal', 'construction', 'validation', 'analysis', 'review', 'decision')",
            name=op.f("ck_architecture_agent_runs_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'awaiting_clarification', 'candidate_ready', 'failed', 'cancelled', 'accepted', 'rejected')",
            name=op.f("ck_architecture_agent_runs_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('queued', 'running')", name=op.f("ck_architecture_agent_runs_stored_after_a_pass")
        ),
        sa.CheckConstraint(
            "(base_architecture_id IS NULL) = (base_revision_number IS NULL)",
            name=op.f("ck_architecture_agent_runs_base_complete"),
        ),
        sa.CheckConstraint(
            "(raw_output_sha256 IS NULL) = (raw_output_bytes IS NULL)",
            name=op.f("ck_architecture_agent_runs_raw_output_complete"),
        ),
        sa.CheckConstraint(
            "decision_reason IS NULL OR char_length(decision_reason) BETWEEN 1 AND 2000",
            name=op.f("ck_architecture_agent_runs_decision_reason_length"),
        ),
        sa.CheckConstraint(
            "model IS NULL OR char_length(model) BETWEEN 1 AND 128",
            name=op.f("ck_architecture_agent_runs_model_length"),
        ),
        sa.CheckConstraint(
            "prompt_version IS NULL OR char_length(prompt_version) BETWEEN 1 AND 64",
            name=op.f("ck_architecture_agent_runs_prompt_version_length"),
        ),
        sa.ForeignKeyConstraint(
            ["accepted_architecture_id", "accepted_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_architecture_agent_runs_accepted_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["accepted_architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_architecture_agent_runs_accepted_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["base_architecture_id", "base_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_architecture_agent_runs_base_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["base_architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_architecture_agent_runs_base_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_architecture_agent_runs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_set_id", "project_id"],
            ["requirement_sets.id", "requirement_sets.project_id"],
            name="fk_architecture_agent_runs_requirement_sets",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_architecture_agent_runs")),
    )
    op.create_index(
        "ix_architecture_agent_runs_accepted",
        "architecture_agent_runs",
        ["accepted_architecture_id", "accepted_revision_number"],
        unique=False,
    )
    op.create_index(
        "ix_architecture_agent_runs_base",
        "architecture_agent_runs",
        ["base_architecture_id", "base_revision_number"],
        unique=False,
    )
    op.create_index(
        "ix_architecture_agent_runs_project_listing",
        "architecture_agent_runs",
        ["project_id", "requested_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_architecture_agent_runs_requirement_set",
        "architecture_agent_runs",
        ["requirement_set_id", "project_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    _create_guard()


def downgrade() -> None:
    _drop_guard()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_architecture_agent_runs_requirement_set", table_name="architecture_agent_runs")
    op.drop_index("ix_architecture_agent_runs_project_listing", table_name="architecture_agent_runs")
    op.drop_index("ix_architecture_agent_runs_base", table_name="architecture_agent_runs")
    op.drop_index("ix_architecture_agent_runs_accepted", table_name="architecture_agent_runs")
    op.drop_table("architecture_agent_runs")
    # ### end Alembic commands ###


# What a pass or a person's decision writes; everything else is the request and never changes.
MUTABLE = (
    "status", "stage", "usage", "model", "prompt_version", "questions", "answers", "proposal",
    "rejections", "candidate", "candidate_content_hash", "reports", "raw_output_sha256",
    "raw_output_bytes", "failure", "accepted_architecture_id", "accepted_revision_number",
    "decision_reason", "history", "limitations", "completed_at", "updated_at",
)  # fmt: skip
FINISHED = "('failed', 'cancelled', 'accepted', 'rejected')"


def _create_guard() -> None:
    kept = "ARRAY[" + ", ".join(f"'{c}'" for c in MUTABLE) + "]::text[]"
    op.execute(
        f"""
        CREATE FUNCTION architecture_agent_runs_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'TRUNCATE' THEN
                RAISE EXCEPTION '% cannot be truncated', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF TG_OP = 'DELETE' THEN
                IF OLD.status = 'accepted' THEN
                    RAISE EXCEPTION '%: an accepted run is kept', TG_TABLE_NAME
                        USING ERRCODE = 'insufficient_privilege';
                END IF;
                RETURN OLD;
            END IF;
            IF OLD.status IN {FINISHED} THEN
                RAISE EXCEPTION '%: a finished run does not change', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF (to_jsonb(NEW) - {kept}) IS DISTINCT FROM (to_jsonb(OLD) - {kept}) THEN
                RAISE EXCEPTION '%: the request of a run does not change', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF OLD.candidate IS NOT NULL AND (
                NEW.candidate IS DISTINCT FROM OLD.candidate
                OR NEW.candidate_content_hash IS DISTINCT FROM OLD.candidate_content_hash
            ) THEN
                RAISE EXCEPTION '%: a candidate is the one reviewed', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER architecture_agent_runs_guard BEFORE UPDATE OR DELETE ON architecture_agent_runs "
        "FOR EACH ROW EXECUTE FUNCTION architecture_agent_runs_guard()"
    )
    op.execute(
        "CREATE TRIGGER architecture_agent_runs_no_truncate BEFORE TRUNCATE ON architecture_agent_runs "
        "FOR EACH STATEMENT EXECUTE FUNCTION architecture_agent_runs_guard()"
    )


def _drop_guard() -> None:
    op.execute("DROP TRIGGER architecture_agent_runs_no_truncate ON architecture_agent_runs")
    op.execute("DROP TRIGGER architecture_agent_runs_guard ON architecture_agent_runs")
    op.execute("DROP FUNCTION architecture_agent_runs_guard()")
