"""migration plan versions

A migration plan is the sequence of its versions; each version records one generated proposal (steps
and dependencies, risks, data migrations, downtime and compatibility, checkpoints, rollback
considerations, findings, evidence, rule and model versions) with the request it answered, between an
exact source revision and an exact target — a later revision of the same architecture, or an
evolution candidate (analysis and candidate id) on the source revision. Revisions are referenced by
same-architecture foreign keys; the architecture is never copied.

Only a version's review status and review history change, by people: a trigger refuses any other
change, any deletion and truncation. Nothing here executes a migration.

Downgrading removes the table and every stored migration plan with it.

Revision ID: 0020
Revises: 0019
Create Date: 2026-10-01 12:43:12.438398+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "migration_plan_versions",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("source_revision_number", sa.Integer(), nullable=False),
        sa.Column("source_content_hash", sa.Text(), nullable=False),
        sa.Column("target_kind", sa.Text(), nullable=False),
        sa.Column("target_revision_number", sa.Integer(), nullable=False),
        sa.Column("target_content_hash", sa.Text(), nullable=False),
        sa.Column("target_analysis_id", sa.Uuid(), nullable=True),
        sa.Column("target_candidate_id", sa.Text(), nullable=True),
        sa.Column("strategy", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("reviews", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(target_kind = 'candidate') = (target_candidate_id IS NOT NULL AND target_analysis_id IS NOT NULL)",
            name=op.f("ck_migration_plan_versions_candidate_target_complete"),
        ),
        sa.CheckConstraint(
            "fingerprint ~ '^[0-9a-f]{64}$'", name=op.f("ck_migration_plan_versions_fingerprint_format")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(proposal) = 'object'", name=op.f("ck_migration_plan_versions_proposal_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(request) = 'object'", name=op.f("ck_migration_plan_versions_request_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(reviews) = 'array'", name=op.f("ck_migration_plan_versions_reviews_array")
        ),
        sa.CheckConstraint(
            "source_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_migration_plan_versions_source_content_hash_format"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'needs_information', 'ready_for_review', 'approved', 'rejected', 'superseded', 'archived')",
            name=op.f("ck_migration_plan_versions_status"),
        ),
        sa.CheckConstraint(
            "target_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_migration_plan_versions_target_content_hash_format"),
        ),
        sa.CheckConstraint(
            "target_kind = 'candidate' OR target_revision_number > source_revision_number",
            name=op.f("ck_migration_plan_versions_target_after_source"),
        ),
        sa.CheckConstraint(
            "target_kind IN ('revision', 'candidate')", name=op.f("ck_migration_plan_versions_target_kind")
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 200", name=op.f("ck_migration_plan_versions_title_length")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_migration_plan_versions_version_positive")),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_migration_plan_versions_architecture_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "source_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_migration_plan_versions_source_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "target_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_migration_plan_versions_target_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_migration_plan_versions")),
        sa.UniqueConstraint("plan_id", "version", name=op.f("uq_migration_plan_versions_plan_id_version")),
    )
    op.create_index(
        "ix_migration_plan_versions_project_listing",
        "migration_plan_versions",
        ["project_id", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###
    _create_guard()


def downgrade() -> None:
    _drop_guard()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_migration_plan_versions_project_listing", table_name="migration_plan_versions")
    op.drop_table("migration_plan_versions")
    # ### end Alembic commands ###


REVIEWED = ("status", "reviews", "updated_at")  # the only columns a review changes


def _create_guard() -> None:
    # A version is what was reviewed and approved: rewriting its content would make the review
    # meaningless. Only its review status and history change; deleting it is an error.
    kept = " - ".join(f"'{c}'" for c in REVIEWED)
    op.execute(
        f"""
        CREATE FUNCTION migration_plan_versions_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP <> 'UPDATE' THEN
                RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF (to_jsonb(NEW) - {kept}) IS DISTINCT FROM (to_jsonb(OLD) - {kept}) THEN
                RAISE EXCEPTION '%: only the review status and history of a version change', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER migration_plan_versions_guard BEFORE UPDATE OR DELETE ON migration_plan_versions "
        "FOR EACH ROW EXECUTE FUNCTION migration_plan_versions_guard()"
    )
    op.execute(
        "CREATE TRIGGER migration_plan_versions_no_truncate BEFORE TRUNCATE ON migration_plan_versions "
        "FOR EACH STATEMENT EXECUTE FUNCTION migration_plan_versions_guard()"
    )


def _drop_guard() -> None:
    op.execute("DROP TRIGGER migration_plan_versions_no_truncate ON migration_plan_versions")
    op.execute("DROP TRIGGER migration_plan_versions_guard ON migration_plan_versions")
    op.execute("DROP FUNCTION migration_plan_versions_guard()")
