"""observability analyses

An observability analysis records one execution of the deterministic observability engine against
one architecture revision: the request's inputs (scope, analyzers, requirement ids, assumptions), the
project's policy as it was, and the in-force requirements it read (id, version, status); the analyzer
set, fingerprints, coverage summary, requirement and policy checks, what could not run, and
limitations. Components (with a coverage state per dimension) and findings are rows of their own, for
paging and filtering; findings keep their priority position and stable id, and a finding's type fixes
its category and basis. No telemetry is stored — only what the architecture declares and what was
concluded from it — and no secret: evidence shows the names of secret-looking settings, never values.

The three tables are append-only (triggers, with the guard function of requirement sets, 0004): an
analysis is stored once, finished. Analyses reference their architecture and revision, and rows
their analysis, through same-project foreign keys.

Downgrading removes the three tables and every stored observability analysis with them.

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-27 11:42:46.858915+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

TABLES = ("observability_analyses", "observability_components", "observability_findings")

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observability_analyses",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("architecture_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("revision_content_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("analyzer_set", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context_fingerprint", sa.Text(), nullable=True),
        sa.Column("result_fingerprint", sa.Text(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unsupported", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(checks) = 'array'", name=op.f("ck_observability_analyses_checks_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(inputs) = 'object'", name=op.f("ck_observability_analyses_inputs_object")
        ),
        sa.CheckConstraint(
            "revision_content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_observability_analyses_revision_content_hash_format"),
        ),
        sa.CheckConstraint(
            "status <> 'failed' OR (completed_at IS NOT NULL AND error_code IS NOT NULL)",
            name=op.f("ck_observability_analyses_failed_has_error"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'partial', 'insufficient_input', 'unsupported', 'failed')",
            name=op.f("ck_observability_analyses_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'failed') OR (completed_at IS NOT NULL AND result_fingerprint IS NOT NULL AND summary IS NOT NULL AND analyzer_set IS NOT NULL)",
            name=op.f("ck_observability_analyses_finished_has_result"),
        ),
        sa.CheckConstraint(
            "label IS NULL OR char_length(label) BETWEEN 1 AND 100",
            name=op.f("ck_observability_analyses_label_length"),
        ),
        sa.CheckConstraint(
            "revision_number >= 1", name=op.f("ck_observability_analyses_revision_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_observability_analyses_architecture_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["architecture_id", "revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_observability_analyses_revision_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observability_analyses")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_observability_analyses_id_project_id")),
    )
    op.create_index(
        op.f("ix_observability_analyses_architecture_id_requested_at_id"),
        "observability_analyses",
        ["architecture_id", "requested_at", "id"],
        unique=False,
    )
    op.create_table(
        "observability_components",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("criticality", sa.Text(), nullable=True),
        sa.Column("logging", sa.Text(), nullable=False),
        sa.Column("metrics", sa.Text(), nullable=False),
        sa.Column("tracing", sa.Text(), nullable=False),
        sa.Column("health_checks", sa.Text(), nullable=False),
        sa.Column("alerting", sa.Text(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "alerting IN ('modeled', 'partial', 'absent', 'unknown', 'unsupported')",
            name=op.f("ck_observability_components_alerting"),
        ),
        sa.CheckConstraint(
            "criticality IS NULL OR criticality IN ('critical', 'standard')",
            name=op.f("ck_observability_components_criticality"),
        ),
        sa.CheckConstraint(
            "health_checks IN ('modeled', 'partial', 'absent', 'unknown', 'unsupported')",
            name=op.f("ck_observability_components_health_checks"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(data) = 'object'", name=op.f("ck_observability_components_data_object")
        ),
        sa.CheckConstraint(
            "logging IN ('modeled', 'partial', 'absent', 'unknown', 'unsupported')",
            name=op.f("ck_observability_components_logging"),
        ),
        sa.CheckConstraint(
            "metrics IN ('modeled', 'partial', 'absent', 'unknown', 'unsupported')",
            name=op.f("ck_observability_components_metrics"),
        ),
        sa.CheckConstraint(
            "tracing IN ('modeled', 'partial', 'absent', 'unknown', 'unsupported')",
            name=op.f("ck_observability_components_tracing"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id", "project_id"],
            ["observability_analyses.id", "observability_analyses.project_id"],
            name="fk_observability_components_analysis_observability_analyses",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observability_components")),
        sa.UniqueConstraint(
            "analysis_id", "node_id", name=op.f("uq_observability_components_analysis_id_node_id")
        ),
    )
    op.create_table(
        "observability_findings",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("finding_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("category", sa.Text(), nullable=False),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("certainty", sa.Text(), nullable=False),
        sa.Column("dimension", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(type = 'alert_delivery_not_modeled' AND category = 'alerting' AND basis = 'not_evaluable') OR (type = 'alert_without_signal' AND category = 'alerting' AND basis = 'control_gap') OR (type = 'alerts_absent' AND category = 'alerting' AND basis = 'control_gap') OR (type = 'alerts_not_modeled' AND category = 'alerting' AND basis = 'not_evaluable') OR (type = 'criticality_not_modeled' AND category = 'criticality' AND basis = 'not_evaluable') OR (type = 'health_check_absent' AND category = 'health_checks' AND basis = 'control_gap') OR (type = 'health_check_not_modeled' AND category = 'health_checks' AND basis = 'not_evaluable') OR (type = 'health_check_unconsumed' AND category = 'health_checks' AND basis = 'not_evaluable') OR (type = 'logs_absent' AND category = 'logging' AND basis = 'control_gap') OR (type = 'logs_not_modeled' AND category = 'logging' AND basis = 'not_evaluable') OR (type = 'metrics_absent' AND category = 'metrics' AND basis = 'control_gap') OR (type = 'metrics_not_modeled' AND category = 'metrics' AND basis = 'not_evaluable') OR (type = 'policy_not_evaluable' AND category = 'policy' AND basis = 'not_evaluable') OR (type = 'policy_violated' AND category = 'policy' AND basis = 'violation') OR (type = 'propagation_broken' AND category = 'tracing' AND basis = 'control_gap') OR (type = 'propagation_not_modeled' AND category = 'tracing' AND basis = 'not_evaluable') OR (type = 'requirement_not_evaluable' AND category = 'requirement' AND basis = 'not_evaluable') OR (type = 'requirement_violated' AND category = 'requirement' AND basis = 'violation') OR (type = 'sensitive_data_in_logs' AND category = 'logging' AND basis = 'potential_risk') OR (type = 'telemetry_not_collected' AND category = 'collection' AND basis = 'not_evaluable') OR (type = 'traces_absent' AND category = 'tracing' AND basis = 'control_gap') OR (type = 'traces_not_modeled' AND category = 'tracing' AND basis = 'not_evaluable')",
            name=op.f("ck_observability_findings_type_fixes_category_and_basis"),
        ),
        sa.CheckConstraint(
            "basis IN ('control_gap', 'potential_risk', 'violation', 'not_evaluable')",
            name=op.f("ck_observability_findings_basis"),
        ),
        sa.CheckConstraint(
            "category IN ('logging', 'metrics', 'tracing', 'health_checks', 'alerting', 'collection', 'criticality', 'requirement', 'policy')",
            name=op.f("ck_observability_findings_category"),
        ),
        sa.CheckConstraint(
            "certainty IN ('modeled', 'candidate')", name=op.f("ck_observability_findings_certainty")
        ),
        sa.CheckConstraint(
            "dimension IS NULL OR dimension IN ('logging', 'metrics', 'tracing', 'health_checks', 'alerting')",
            name=op.f("ck_observability_findings_dimension"),
        ),
        sa.CheckConstraint(
            "finding_id ~ '^obs_[0-9a-f]{16}$'", name=op.f("ck_observability_findings_finding_id_format")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(data) = 'object'", name=op.f("ck_observability_findings_data_object")
        ),
        sa.CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low', 'info')",
            name=op.f("ck_observability_findings_severity"),
        ),
        sa.CheckConstraint(
            "type IN ('criticality_not_modeled', 'logs_absent', 'logs_not_modeled', 'sensitive_data_in_logs', 'metrics_absent', 'metrics_not_modeled', 'traces_absent', 'traces_not_modeled', 'propagation_broken', 'propagation_not_modeled', 'telemetry_not_collected', 'health_check_absent', 'health_check_not_modeled', 'health_check_unconsumed', 'alerts_absent', 'alerts_not_modeled', 'alert_without_signal', 'alert_delivery_not_modeled', 'requirement_violated', 'requirement_not_evaluable', 'policy_violated', 'policy_not_evaluable')",
            name=op.f("ck_observability_findings_type"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_observability_findings_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["analysis_id", "project_id"],
            ["observability_analyses.id", "observability_analyses.project_id"],
            name="fk_observability_findings_analysis_observability_analyses",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observability_findings")),
        sa.UniqueConstraint(
            "analysis_id", "finding_id", name=op.f("uq_observability_findings_analysis_id_finding_id")
        ),
        sa.UniqueConstraint(
            "analysis_id", "position", name=op.f("uq_observability_findings_analysis_id_position")
        ),
    )
    # ### end Alembic commands ###
    for table in TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION requirement_sets_reject_change()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            "FOR EACH STATEMENT EXECUTE FUNCTION requirement_sets_reject_change()"
        )


def downgrade() -> None:
    for table in reversed(TABLES):
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_append_only ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("observability_findings")
    op.drop_table("observability_components")
    op.drop_index(
        op.f("ix_observability_analyses_architecture_id_requested_at_id"), table_name="observability_analyses"
    )
    op.drop_table("observability_analyses")
    # ### end Alembic commands ###
