"""discovery runs

A discovery run records one discovery over supplied artifacts: what was requested (source type,
label, an optional baseline revision referenced by same-project foreign keys), who and when, and its
result — artifacts by path, hash and size (never their content), findings with secrets redacted,
candidates, relationships, diagnostics, the proposed architecture and its validation — or why it
failed. Nothing here is an architecture: an accepted proposal is stored as a revision through the
architecture workflow, and the run records which.

Only a run's review decisions and acceptances change, by people: a trigger refuses any other change,
the deletion of a run an acceptance refers to, and truncation.

Downgrading removes the table and every stored discovery run with it.

Revision ID: 0021
Revises: 0020
Create Date: 2026-10-02 09:26:42.753366+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0021"
down_revision: str | None = "0020"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovery_runs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("source_type", sa.Text(), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("baseline_architecture_id", sa.Uuid(), nullable=True),
        sa.Column("baseline_revision_number", sa.Integer(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fingerprint", sa.Text(), nullable=True),
        sa.Column("sources_fingerprint", sa.Text(), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("decisions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("acceptances", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'failed') = (error IS NOT NULL)", name=op.f("ck_discovery_runs_error_when_failed")
        ),
        sa.CheckConstraint(
            "(status IN ('completed', 'completed_with_warnings')) = (result IS NOT NULL AND summary IS NOT NULL AND fingerprint IS NOT NULL AND sources_fingerprint IS NOT NULL)",
            name=op.f("ck_discovery_runs_result_when_completed"),
        ),
        sa.CheckConstraint(
            "fingerprint IS NULL OR fingerprint ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_discovery_runs_fingerprint_format"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(acceptances) = 'array'", name=op.f("ck_discovery_runs_acceptances_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(decisions) = 'array'", name=op.f("ck_discovery_runs_decisions_array")
        ),
        sa.CheckConstraint(
            "result IS NULL OR jsonb_typeof(result) = 'object'", name=op.f("ck_discovery_runs_result_object")
        ),
        sa.CheckConstraint(
            "source_type IS NULL OR source_type IN ('kubernetes', 'docker_compose', 'terraform_json', 'architecture_json')",
            name=op.f("ck_discovery_runs_source_type"),
        ),
        sa.CheckConstraint(
            "sources_fingerprint IS NULL OR sources_fingerprint ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_discovery_runs_sources_fingerprint_format"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'completed', 'completed_with_warnings', 'failed', 'cancelled')",
            name=op.f("ck_discovery_runs_status"),
        ),
        sa.CheckConstraint(
            "(baseline_architecture_id IS NULL) = (baseline_revision_number IS NULL)",
            name=op.f("ck_discovery_runs_baseline_complete"),
        ),
        sa.CheckConstraint(
            "label IS NULL OR char_length(label) BETWEEN 1 AND 200",
            name=op.f("ck_discovery_runs_label_length"),
        ),
        sa.CheckConstraint(
            "result IS NULL OR octet_length(result::text) <= 33554432",
            name=op.f("ck_discovery_runs_result_size"),
        ),
        sa.ForeignKeyConstraint(
            ["baseline_architecture_id", "baseline_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_discovery_runs_baseline_architecture_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["baseline_architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_discovery_runs_baseline_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_discovery_runs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovery_runs")),
    )
    op.create_index(
        "ix_discovery_runs_baseline",
        "discovery_runs",
        ["baseline_architecture_id", "baseline_revision_number"],
        unique=False,
    )
    op.create_index(
        "ix_discovery_runs_project_listing",
        "discovery_runs",
        ["project_id", "requested_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###
    _create_guard()


def downgrade() -> None:
    _drop_guard()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_discovery_runs_project_listing", table_name="discovery_runs")
    op.drop_index("ix_discovery_runs_baseline", table_name="discovery_runs")
    op.drop_table("discovery_runs")
    # ### end Alembic commands ###


REVIEWED = ("decisions", "acceptances", "updated_at")  # the only columns a review changes


def _create_guard() -> None:
    # A run is the evidence a review rests on: rewriting its result would make the review meaningless.
    # Only its decisions and acceptances change; an accepted run is the provenance of a revision.
    kept = " - ".join(f"'{c}'" for c in REVIEWED)
    op.execute(
        f"""
        CREATE FUNCTION discovery_runs_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP = 'TRUNCATE' THEN
                RAISE EXCEPTION '% cannot be truncated', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF TG_OP = 'DELETE' THEN
                IF jsonb_array_length(OLD.acceptances) > 0 THEN
                    RAISE EXCEPTION '%: an accepted run is kept', TG_TABLE_NAME
                        USING ERRCODE = 'insufficient_privilege';
                END IF;
                RETURN OLD;
            END IF;
            IF (to_jsonb(NEW) - {kept}) IS DISTINCT FROM (to_jsonb(OLD) - {kept}) THEN
                RAISE EXCEPTION '%: only the decisions and acceptances of a run change', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER discovery_runs_guard BEFORE UPDATE OR DELETE ON discovery_runs "
        "FOR EACH ROW EXECUTE FUNCTION discovery_runs_guard()"
    )
    op.execute(
        "CREATE TRIGGER discovery_runs_no_truncate BEFORE TRUNCATE ON discovery_runs "
        "FOR EACH STATEMENT EXECUTE FUNCTION discovery_runs_guard()"
    )


def _drop_guard() -> None:
    op.execute("DROP TRIGGER discovery_runs_no_truncate ON discovery_runs")
    op.execute("DROP TRIGGER discovery_runs_guard ON discovery_runs")
    op.execute("DROP FUNCTION discovery_runs_guard()")
