"""project listing index

Replaces ix_projects_organization_id_status_created_at_id with (organization_id, created_at, id):
with status in the middle of the key, the default listing (no status filter, newest first)
could not take its order from the index and sorted every project of the organization.
Found by tests/integration/database/test_query_plans.py. The projects table is small; on a large
one this would be built with CREATE INDEX CONCURRENTLY outside a transaction.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-25 18:29:20.030822+00:00
"""

from collections.abc import Sequence

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # New index first: the RESTRICT check on organizations(id) always has an index to use.
    op.create_index(
        op.f("ix_projects_organization_id_created_at_id"),
        "projects",
        ["organization_id", "created_at", "id"],
        unique=False,
    )
    op.drop_index(op.f("ix_projects_organization_id_status_created_at_id"), table_name="projects")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_organization_id_created_at_id"), table_name="projects")
    op.create_index(
        op.f("ix_projects_organization_id_status_created_at_id"),
        "projects",
        ["organization_id", "status", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###
