"""architecture workflows

An architecture workflow records one bounded run from a goal to a review package: the request (goal
and budget, who and when), where it stands, what it used, the requirement analysis and pinned set it
designed against (same-project foreign keys), what it waits for, the candidates selected for review and
— a person's decision — the revision it became or why it was rejected. The row is also its job: a
worker claims it under a lease (owner and expiry, present exactly while running).

Its candidates keep their architecture (the IR's JSON, checked against its content hash on read) and
lineage (a parent of the same workflow) forever; only their status and engine reports change. Its
steps — the checkpoints, one per operation key and attempt — are append-only.

Triggers keep the record honest: a workflow's request never changes and a finished one never changes;
a candidate's architecture and lineage never change; steps are never updated; nothing is deleted or
truncated.

Downgrading removes the three tables and every stored workflow with them (the revisions approved from
them are kept: they are ordinary revisions).

Revision ID: 0026
Revises: 0025
Create Date: 2026-10-03 14:54:07.795749+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0026"
down_revision: str | None = "0025"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "architecture_workflows",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("goal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("budget", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requirement_analysis_id", sa.Uuid(), nullable=True),
        sa.Column("requirement_set_id", sa.Uuid(), nullable=True),
        sa.Column("input_request", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selected", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_candidate_id", sa.Uuid(), nullable=True),
        sa.Column("approved_architecture_id", sa.Uuid(), nullable=True),
        sa.Column("approved_revision_number", sa.Integer(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("failure", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("history", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_owner", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'approved') = (approved_candidate_id IS NOT NULL AND approved_architecture_id IS NOT NULL AND approved_revision_number IS NOT NULL)",
            name=op.f("ck_architecture_workflows_revision_when_approved"),
        ),
        sa.CheckConstraint(
            "(status = 'failed') = (failure IS NOT NULL)",
            name=op.f("ck_architecture_workflows_failure_when_failed"),
        ),
        sa.CheckConstraint(
            "(status = 'needs_input') = (input_request IS NOT NULL)",
            name=op.f("ck_architecture_workflows_input_when_waiting"),
        ),
        sa.CheckConstraint(
            "(status = 'rejected') = (decision_reason IS NOT NULL)",
            name=op.f("ck_architecture_workflows_reason_when_rejected"),
        ),
        sa.CheckConstraint(
            "(status = 'running') = (lease_owner IS NOT NULL AND lease_expires_at IS NOT NULL)",
            name=op.f("ck_architecture_workflows_lease_when_running"),
        ),
        sa.CheckConstraint(
            "(status IN ('approved', 'rejected', 'cancelled', 'failed')) = (completed_at IS NOT NULL)",
            name=op.f("ck_architecture_workflows_completed_when_finished"),
        ),
        sa.CheckConstraint(
            "failure IS NULL OR jsonb_typeof(failure) = 'object'",
            name=op.f("ck_architecture_workflows_failure_object"),
        ),
        sa.CheckConstraint(
            "input_request IS NULL OR jsonb_typeof(input_request) = 'object'",
            name=op.f("ck_architecture_workflows_input_request_object"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(answers) = 'array'", name=op.f("ck_architecture_workflows_answers_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(budget) = 'object'", name=op.f("ck_architecture_workflows_budget_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(goal) = 'object'", name=op.f("ck_architecture_workflows_goal_object")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(history) = 'array'", name=op.f("ck_architecture_workflows_history_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(limitations) = 'array'", name=op.f("ck_architecture_workflows_limitations_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(selected) = 'array'", name=op.f("ck_architecture_workflows_selected_array")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(usage) = 'object'", name=op.f("ck_architecture_workflows_usage_object")
        ),
        sa.CheckConstraint(
            "stage IN ('intake', 'requirements', 'knowledge_retrieval', 'generation', 'validation', 'analysis', 'iteration', 'comparison', 'review', 'decision')",
            name=op.f("ck_architecture_workflows_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'needs_input', 'review_ready', 'approved', 'rejected', 'cancelled', 'failed')",
            name=op.f("ck_architecture_workflows_status"),
        ),
        sa.CheckConstraint(
            "decision_reason IS NULL OR char_length(decision_reason) BETWEEN 1 AND 2000",
            name=op.f("ck_architecture_workflows_decision_reason_length"),
        ),
        sa.CheckConstraint("iteration >= 0", name=op.f("ck_architecture_workflows_iteration_non_negative")),
        sa.CheckConstraint(
            "lease_owner IS NULL OR char_length(lease_owner) BETWEEN 1 AND 128",
            name=op.f("ck_architecture_workflows_lease_owner_length"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_architecture_id", "approved_revision_number"],
            ["architecture_revisions.architecture_id", "architecture_revisions.number"],
            name="fk_architecture_workflows_approved_revisions",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["approved_architecture_id", "project_id"],
            ["architectures.id", "architectures.project_id"],
            name="fk_architecture_workflows_approved_architectures",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_architecture_workflows_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_analysis_id", "project_id"],
            ["requirement_analyses.id", "requirement_analyses.project_id"],
            name="fk_architecture_workflows_requirement_analyses",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_set_id", "project_id"],
            ["requirement_sets.id", "requirement_sets.project_id"],
            name="fk_architecture_workflows_requirement_sets",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_architecture_workflows")),
        sa.UniqueConstraint("id", "project_id", name=op.f("uq_architecture_workflows_id_project_id")),
    )
    op.create_index(
        "ix_architecture_workflows_approved",
        "architecture_workflows",
        ["approved_architecture_id", "approved_revision_number"],
        unique=False,
    )
    op.create_index(
        "ix_architecture_workflows_claimable",
        "architecture_workflows",
        ["status", "lease_expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_architecture_workflows_project_listing",
        "architecture_workflows",
        ["project_id", "requested_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_architecture_workflows_requirement_analysis",
        "architecture_workflows",
        ["requirement_analysis_id", "project_id"],
        unique=False,
    )
    op.create_index(
        "ix_architecture_workflows_requirement_set",
        "architecture_workflows",
        ["requirement_set_id", "project_id"],
        unique=False,
    )
    op.create_table(
        "workflow_candidates",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("ir", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("trigger", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
        sa.Column("rule", sa.Text(), nullable=True),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("reports", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(origin = 'rule') = (rule IS NOT NULL)", name=op.f("ck_workflow_candidates_rule_when_by_rule")
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_workflow_candidates_content_hash_format")
        ),
        sa.CheckConstraint("jsonb_typeof(ir) = 'object'", name=op.f("ck_workflow_candidates_ir_object")),
        sa.CheckConstraint(
            "jsonb_typeof(reports) = 'array'", name=op.f("ck_workflow_candidates_reports_array")
        ),
        sa.CheckConstraint(
            "origin IN ('agent', 'rule', 'agent_revision')", name=op.f("ck_workflow_candidates_origin")
        ),
        sa.CheckConstraint(
            "status IN ('generated', 'validated', 'rejected', 'superseded', 'selected_for_review', 'accepted')",
            name=op.f("ck_workflow_candidates_status"),
        ),
        sa.CheckConstraint(
            "trigger IS NULL OR jsonb_typeof(trigger) = 'object'",
            name=op.f("ck_workflow_candidates_trigger_object"),
        ),
        sa.CheckConstraint(
            "(ordinal = 1) = (parent_id IS NULL)", name=op.f("ck_workflow_candidates_parent_unless_first")
        ),
        sa.CheckConstraint(
            "char_length(reason) BETWEEN 1 AND 500", name=op.f("ck_workflow_candidates_reason_length")
        ),
        sa.CheckConstraint(
            "octet_length(ir::text || reports::text) <= 8388608", name=op.f("ck_workflow_candidates_size")
        ),
        sa.CheckConstraint("ordinal >= 1", name=op.f("ck_workflow_candidates_ordinal_positive")),
        sa.ForeignKeyConstraint(
            ["parent_id", "workflow_id"],
            ["workflow_candidates.id", "workflow_candidates.workflow_id"],
            name="fk_workflow_candidates_parent",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "project_id"],
            ["architecture_workflows.id", "architecture_workflows.project_id"],
            name="fk_workflow_candidates_workflows",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_candidates")),
        sa.UniqueConstraint("id", "workflow_id", name=op.f("uq_workflow_candidates_id_workflow_id")),
        sa.UniqueConstraint(
            "workflow_id", "ordinal", name=op.f("uq_workflow_candidates_workflow_id_ordinal")
        ),
    )
    op.create_index(
        "ix_workflow_candidates_parent", "workflow_candidates", ["parent_id", "workflow_id"], unique=False
    )
    op.create_index(
        "ix_workflow_candidates_workflow",
        "workflow_candidates",
        ["workflow_id", "project_id", "ordinal"],
        unique=False,
    )
    op.create_table(
        "workflow_steps",
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("stage", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=True),
        sa.Column("outputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(status = 'completed') = (error IS NULL)", name=op.f("ck_workflow_steps_error_unless_completed")
        ),
        sa.CheckConstraint(
            "NOT retryable OR status = 'failed'", name=op.f("ck_workflow_steps_retryable_only_when_failed")
        ),
        sa.CheckConstraint(
            "action IN ('analyze_requirements', 'request_clarification', 'retrieve_knowledge', 'generate_architecture', 'validate_architecture', 'run_capacity_analysis', 'run_cost_analysis', 'run_reliability_analysis', 'run_security_analysis', 'run_observability_analysis', 'run_simulation', 'generate_alternative', 'compare_candidates', 'prepare_review')",
            name=op.f("ck_workflow_steps_action"),
        ),
        sa.CheckConstraint("jsonb_typeof(outputs) = 'object'", name=op.f("ck_workflow_steps_outputs_object")),
        sa.CheckConstraint("jsonb_typeof(usage) = 'object'", name=op.f("ck_workflow_steps_usage_object")),
        sa.CheckConstraint(
            "stage IN ('intake', 'requirements', 'knowledge_retrieval', 'generation', 'validation', 'analysis', 'iteration', 'comparison', 'review', 'decision')",
            name=op.f("ck_workflow_steps_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'failed', 'skipped')", name=op.f("ck_workflow_steps_status")
        ),
        sa.CheckConstraint("attempt BETWEEN 1 AND 2", name=op.f("ck_workflow_steps_attempt_bounded")),
        sa.CheckConstraint(
            "completed_at >= started_at", name=op.f("ck_workflow_steps_completed_after_started")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id", "workflow_id"],
            ["workflow_candidates.id", "workflow_candidates.workflow_id"],
            name="fk_workflow_steps_candidates",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id", "project_id"],
            ["architecture_workflows.id", "architecture_workflows.project_id"],
            name="fk_workflow_steps_workflows",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_steps")),
        sa.UniqueConstraint(
            "workflow_id", "key", "attempt", name=op.f("uq_workflow_steps_workflow_id_key_attempt")
        ),
        sa.UniqueConstraint("workflow_id", "ordinal", name=op.f("uq_workflow_steps_workflow_id_ordinal")),
    )
    op.create_index(
        "ix_workflow_steps_candidate", "workflow_steps", ["candidate_id", "workflow_id"], unique=False
    )
    op.create_index(
        "ix_workflow_steps_workflow", "workflow_steps", ["workflow_id", "project_id", "ordinal"], unique=False
    )
    # ### end Alembic commands ###
    _create_guards()


def downgrade() -> None:
    _drop_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_steps_workflow", table_name="workflow_steps")
    op.drop_index("ix_workflow_steps_candidate", table_name="workflow_steps")
    op.drop_table("workflow_steps")
    op.drop_index("ix_workflow_candidates_workflow", table_name="workflow_candidates")
    op.drop_index("ix_workflow_candidates_parent", table_name="workflow_candidates")
    op.drop_table("workflow_candidates")
    op.drop_index("ix_architecture_workflows_requirement_set", table_name="architecture_workflows")
    op.drop_index("ix_architecture_workflows_requirement_analysis", table_name="architecture_workflows")
    op.drop_index("ix_architecture_workflows_project_listing", table_name="architecture_workflows")
    op.drop_index("ix_architecture_workflows_claimable", table_name="architecture_workflows")
    op.drop_index("ix_architecture_workflows_approved", table_name="architecture_workflows")
    op.drop_table("architecture_workflows")
    # ### end Alembic commands ###


# What a worker's step or a person's decision may change; everything else is the request.
WORKFLOW_MUTABLE = (
    "status", "stage", "iteration", "usage", "requirement_analysis_id", "requirement_set_id", "input_request",
    "answers", "selected", "approved_candidate_id", "approved_architecture_id", "approved_revision_number",
    "decision_reason", "failure", "history", "limitations", "started_at", "completed_at", "lease_owner",
    "lease_expires_at", "updated_at",
)  # fmt: skip
CANDIDATE_MUTABLE = ("status", "reports")
TERMINAL = "('approved', 'rejected', 'cancelled', 'failed')"


def _array(names: tuple[str, ...]) -> str:
    return "ARRAY[" + ", ".join(f"'{n}'" for n in names) + "]::text[]"


def _create_guards() -> None:
    kept = _array(WORKFLOW_MUTABLE)
    op.execute(
        f"""
        CREATE FUNCTION architecture_workflows_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP IN ('TRUNCATE', 'DELETE') THEN
                RAISE EXCEPTION '%: a workflow is kept: % is not allowed', TG_TABLE_NAME, TG_OP
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF OLD.status IN {TERMINAL} THEN
                RAISE EXCEPTION '%: a finished workflow does not change', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF (to_jsonb(NEW) - {kept}) IS DISTINCT FROM (to_jsonb(OLD) - {kept}) THEN
                RAISE EXCEPTION '%: the request of a workflow does not change', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    mutable = _array(CANDIDATE_MUTABLE)
    op.execute(
        f"""
        CREATE FUNCTION workflow_candidates_guard() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF TG_OP IN ('TRUNCATE', 'DELETE') THEN
                RAISE EXCEPTION '%: a candidate is kept: % is not allowed', TG_TABLE_NAME, TG_OP
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            IF (to_jsonb(NEW) - {mutable}) IS DISTINCT FROM (to_jsonb(OLD) - {mutable}) THEN
                RAISE EXCEPTION '%: a candidate keeps its architecture and lineage', TG_TABLE_NAME
                    USING ERRCODE = 'insufficient_privilege';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION workflow_steps_reject_change() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% is append-only: % is not allowed', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END;
        $$
        """
    )
    for table, function in (
        ("architecture_workflows", "architecture_workflows_guard"),
        ("workflow_candidates", "workflow_candidates_guard"),
        ("workflow_steps", "workflow_steps_reject_change"),
    ):
        op.execute(
            f"CREATE TRIGGER {table}_guard BEFORE UPDATE OR DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION {function}()"
        )
        op.execute(
            f"CREATE TRIGGER {table}_no_truncate BEFORE TRUNCATE ON {table} "
            f"FOR EACH STATEMENT EXECUTE FUNCTION {function}()"
        )


def _drop_guards() -> None:
    for table in ("workflow_steps", "workflow_candidates", "architecture_workflows"):
        op.execute(f"DROP TRIGGER {table}_no_truncate ON {table}")
        op.execute(f"DROP TRIGGER {table}_guard ON {table}")
    op.execute("DROP FUNCTION workflow_steps_reject_change()")
    op.execute("DROP FUNCTION workflow_candidates_guard()")
    op.execute("DROP FUNCTION architecture_workflows_guard()")
