"""Migration checks against clean databases: apply, roll back, re-apply, and no model drift."""

import asyncio
from collections.abc import Iterator

import asyncpg
import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.engine import make_url

from tests.integration.conftest import alembic_config, create_scratch_database, drop_scratch_database

pytestmark = pytest.mark.integration

AUTH_TABLES = {
    "users",
    "organizations",
    "organization_members",
    "sessions",
    "email_verification_tokens",
    "password_reset_tokens",
    "invitations",
    "audit_logs",
}


@pytest.fixture
def empty_database_url() -> Iterator[str]:
    url = create_scratch_database()
    try:
        yield url
    finally:
        drop_scratch_database(url)


async def _fetch_names(url: str, sql: str) -> set[str]:
    dsn = make_url(url).set(drivername="postgresql").render_as_string(hide_password=False)
    connection = await asyncpg.connect(dsn)
    try:
        return {row[0] for row in await connection.fetch(sql)}
    finally:
        await connection.close()


def _tables(url: str) -> set[str]:
    sql = "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
    return asyncio.run(_fetch_names(url, sql)) - {"alembic_version"}


def _functions(url: str) -> set[str]:
    sql = "SELECT proname FROM pg_proc JOIN pg_namespace n ON n.oid = pronamespace WHERE nspname = 'public'"
    return asyncio.run(_fetch_names(url, sql))


def test_history_is_linear() -> None:
    script = ScriptDirectory.from_config(alembic_config("postgresql+asyncpg://unused/unused"))
    assert len(script.get_heads()) == 1


def test_upgrade_creates_every_auth_table(empty_database_url: str) -> None:
    command.upgrade(alembic_config(empty_database_url), "head")

    assert _tables(empty_database_url) == AUTH_TABLES
    assert "audit_logs_reject_change" in _functions(empty_database_url)


def test_downgrade_removes_everything_and_upgrade_reapplies(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    assert _tables(empty_database_url) == set()
    assert "audit_logs_reject_change" not in _functions(empty_database_url)

    command.upgrade(config, "head")
    assert _tables(empty_database_url) == AUTH_TABLES


def test_models_match_migrations(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as error:  # pragma: no cover - failure path
        pytest.fail(f"persistence/models differ from the migrations: {error}")
