"""Migration checks against clean databases: apply, roll back, re-apply, and no model drift."""

import asyncio
from collections.abc import Iterator

import asyncpg
import pytest
from alembic import command
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.engine import make_url

from tests.integration.conftest import alembic_config, create_scratch_database, drop_scratch_database

pytestmark = pytest.mark.integration

AUTH_TABLES = {
    "users",
    "organizations",
    "organization_members",
    "sessions",
    "email_verification_tokens",
    "password_reset_tokens",
    "invitations",
    "audit_logs",
}
PROJECT_TABLES = {"projects"}
REQUIREMENT_TABLES = {"requirements", "requirement_versions"}
SET_TABLES = {"requirement_sets", "requirement_set_items"}
ANALYSIS_TABLES = {"requirement_analyses"}
ARCHITECTURE_TABLES = {"architectures", "architecture_revisions", "architecture_layouts"}
VALIDATION_TABLES = {"validation_runs", "validation_findings"}
CAPACITY_TABLES = {"capacity_analyses", "capacity_components", "capacity_bottlenecks"}
PRICING_TABLES = {"pricing_snapshots", "pricing_records"}
COST_TABLES = {"cost_analyses", "cost_line_items"}
RELIABILITY_TABLES = {"reliability_analyses", "reliability_components", "reliability_findings"}
SECURITY_TABLES = {"security_analyses", "security_components", "security_findings"}
OBSERVABILITY_TABLES = {"observability_analyses", "observability_components", "observability_findings"}
SIMULATION_TABLES = {"simulations", "simulation_components", "simulation_deltas"}
EVOLUTION_TABLES = {"evolution_analyses", "evolution_candidates", "decisions"}
MIGRATION_TABLES = {"migration_plan_versions"}
DISCOVERY_TABLES = {"discovery_runs"}
DRIFT_TABLES = {"drift_analyses", "drift_items", "drift_identity_mappings"}
KNOWLEDGE_TABLES = {
    "knowledge_sources", "knowledge_ingestion_runs", "knowledge_source_versions", "knowledge_documents",
    "knowledge_chunks",
}  # fmt: skip
AGENT_TABLES = {"architecture_agent_runs"}
DIFF_TABLES = {"architecture_diffs", "architecture_diff_explanations"}
ALL_TABLES = (
    AUTH_TABLES
    | PROJECT_TABLES
    | REQUIREMENT_TABLES
    | SET_TABLES
    | ANALYSIS_TABLES
    | ARCHITECTURE_TABLES
    | VALIDATION_TABLES
    | CAPACITY_TABLES
    | PRICING_TABLES
    | COST_TABLES
    | RELIABILITY_TABLES
    | SECURITY_TABLES
    | OBSERVABILITY_TABLES
    | SIMULATION_TABLES
    | EVOLUTION_TABLES
    | MIGRATION_TABLES
    | DISCOVERY_TABLES
    | DRIFT_TABLES
    | KNOWLEDGE_TABLES
    | AGENT_TABLES
    | DIFF_TABLES
)
GUARDS = {
    "audit_logs_reject_change",
    "requirement_versions_reject_change",
    "requirement_sets_reject_change",
    "migration_plan_versions_guard",
    "discovery_runs_guard",
    "drift_items_guard",
    "knowledge_sources_guard",
    "architecture_agent_runs_guard",
    "architecture_diffs_reject_change",
}


@pytest.fixture
def empty_database_url() -> Iterator[str]:
    url = create_scratch_database()
    try:
        yield url
    finally:
        drop_scratch_database(url)


async def _fetch_names(url: str, sql: str) -> set[str]:
    dsn = make_url(url).set(drivername="postgresql").render_as_string(hide_password=False)
    connection = await asyncpg.connect(dsn)
    try:
        return {row[0] for row in await connection.fetch(sql)}
    finally:
        await connection.close()


def _tables(url: str) -> set[str]:
    sql = "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
    return asyncio.run(_fetch_names(url, sql)) - {"alembic_version"}


def _functions(url: str) -> set[str]:
    sql = "SELECT proname FROM pg_proc JOIN pg_namespace n ON n.oid = pronamespace WHERE nspname = 'public'"
    return asyncio.run(_fetch_names(url, sql))


def test_history_is_linear() -> None:
    script = ScriptDirectory.from_config(alembic_config("postgresql+asyncpg://unused/unused"))
    assert len(script.get_heads()) == 1


def test_upgrade_creates_every_table(empty_database_url: str) -> None:
    command.upgrade(alembic_config(empty_database_url), "head")

    assert _tables(empty_database_url) == ALL_TABLES
    assert _functions(empty_database_url) >= GUARDS


def test_downgrade_removes_everything_and_upgrade_reapplies(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    assert _tables(empty_database_url) == set()
    assert _functions(empty_database_url).isdisjoint(GUARDS)

    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_models_match_migrations(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as error:  # pragma: no cover - failure path
        pytest.fail(f"persistence/models differ from the migrations: {error}")


async def _execute(url: str, sql: str) -> list[tuple[object, ...]]:
    dsn = make_url(url).set(drivername="postgresql").render_as_string(hide_password=False)
    connection = await asyncpg.connect(dsn)
    try:
        return [tuple(row) for row in await connection.fetch(sql)]
    finally:
        await connection.close()


def test_upgrading_an_existing_auth_database_keeps_its_data(empty_database_url: str) -> None:
    """The realistic path: a database already at 0001 (auth) with users and organizations."""
    config = alembic_config(empty_database_url)
    command.upgrade(config, "0001")
    asyncio.run(
        _execute(
            empty_database_url,
            """
            WITH u AS (
                INSERT INTO users (id, email, password_hash, name)
                VALUES (gen_random_uuid(), 'ada@example.com', '$argon2id$x', 'Ada') RETURNING id
            )
            INSERT INTO organizations (id, name) VALUES ('00000000-0000-7000-8000-000000000001', 'Acme')
            """,
        )
    )

    command.upgrade(config, "head")

    assert asyncio.run(_execute(empty_database_url, "SELECT email FROM users")) == [("ada@example.com",)]
    asyncio.run(
        _execute(
            empty_database_url,
            """
            INSERT INTO projects (id, organization_id, name, slug)
            VALUES (gen_random_uuid(), '00000000-0000-7000-8000-000000000001',
                    'Food Delivery', 'food-delivery')
            """,
        )
    )
    assert asyncio.run(_execute(empty_database_url, "SELECT slug FROM projects")) == [("food-delivery",)]


def test_downgrading_projects_leaves_the_auth_schema_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0001")
    assert _tables(empty_database_url) == AUTH_TABLES


def test_downgrading_requirements_leaves_projects_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0002")
    assert _tables(empty_database_url) == AUTH_TABLES | PROJECT_TABLES
    assert "requirement_versions_reject_change" not in _functions(empty_database_url)
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_requirement_sets_leaves_requirements_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0003")
    assert _tables(empty_database_url) == AUTH_TABLES | PROJECT_TABLES | REQUIREMENT_TABLES
    assert "requirement_sets_reject_change" not in _functions(empty_database_url)
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_upgrading_existing_requirements_gives_them_the_system_scope(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "0005")
    asyncio.run(
        _execute(
            empty_database_url,
            """
            WITH o AS (
                INSERT INTO organizations (id, name)
                VALUES ('00000000-0000-7000-8000-000000000001', 'Acme') RETURNING id
            ), p AS (
                INSERT INTO projects (id, organization_id, name, slug)
                SELECT '00000000-0000-7000-8000-000000000002', o.id, 'Food', 'food' FROM o RETURNING id
            ), r AS (
                INSERT INTO requirements (id, project_id, number, current_version, type, category, title,
                                          statement, priority, status, source)
                SELECT '00000000-0000-7000-8000-000000000003', p.id, 1, 1, 'functional', 'order', 't', 's',
                       'low', 'draft', 'user'
                FROM p RETURNING id
            )
            INSERT INTO requirement_versions (id, requirement_id, version, type, category, title, statement,
                                              priority, status, source)
            SELECT gen_random_uuid(), r.id, 1, 'functional', 'order', 't', 's', 'low', 'draft', 'user' FROM r
            """,
        )
    )

    command.upgrade(config, "head")

    rows = asyncio.run(
        _execute(
            empty_database_url,
            "SELECT scope FROM requirements UNION ALL SELECT scope FROM requirement_versions",
        )
    )
    assert rows == [("system",), ("system",)]
    command.downgrade(config, "0005")  # no row uses a new source or scope: downgrading is possible
    command.upgrade(config, "head")


def test_downgrading_analyses_leaves_requirement_sets_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0006")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - ANALYSIS_TABLES
        - ARCHITECTURE_TABLES
        - VALIDATION_TABLES
        - CAPACITY_TABLES
        - PRICING_TABLES
        - COST_TABLES
        - RELIABILITY_TABLES
        - SECURITY_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_validation_leaves_architectures_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0010")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - VALIDATION_TABLES
        - CAPACITY_TABLES
        - PRICING_TABLES
        - COST_TABLES
        - RELIABILITY_TABLES
        - SECURITY_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_capacity_leaves_validation_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0011")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - CAPACITY_TABLES
        - PRICING_TABLES
        - COST_TABLES
        - RELIABILITY_TABLES
        - SECURITY_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_pricing_leaves_capacity_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0012")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - PRICING_TABLES
        - COST_TABLES
        - RELIABILITY_TABLES
        - SECURITY_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_cost_leaves_pricing_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0013")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - COST_TABLES
        - RELIABILITY_TABLES
        - SECURITY_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_reliability_leaves_cost_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0014")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - RELIABILITY_TABLES
        - SECURITY_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_security_leaves_reliability_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0015")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - SECURITY_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_observability_leaves_security_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0016")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_evolution_leaves_simulations_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0018")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_simulations_leaves_observability_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0017")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_migration_plans_leaves_evolution_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0019")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
    )
    assert "migration_plan_versions_guard" not in _functions(empty_database_url)
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_architectures_leaves_requirements_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0007")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES
        - MIGRATION_TABLES
        - DISCOVERY_TABLES
        - DRIFT_TABLES
        - KNOWLEDGE_TABLES
        - AGENT_TABLES
        - DIFF_TABLES
        - ARCHITECTURE_TABLES
        - VALIDATION_TABLES
        - CAPACITY_TABLES
        - PRICING_TABLES
        - COST_TABLES
        - RELIABILITY_TABLES
        - SECURITY_TABLES
        - OBSERVABILITY_TABLES
        - SIMULATION_TABLES
        - EVOLUTION_TABLES
    )
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_upgrading_existing_architectures_keeps_them_and_names_them(empty_database_url: str) -> None:
    """0009 (many architectures per project) keeps every existing architecture and revision, and
    names each architecture after its current revision's IR title."""
    config = alembic_config(empty_database_url)
    command.upgrade(config, "0008")
    asyncio.run(
        _execute(
            empty_database_url,
            """
            WITH o AS (
                INSERT INTO organizations (id, name)
                VALUES ('00000000-0000-7000-8000-000000000001', 'Acme') RETURNING id
            ), p AS (
                INSERT INTO projects (id, organization_id, name, slug)
                SELECT '00000000-0000-7000-8000-000000000002', o.id, 'Food', 'food' FROM o RETURNING id
            ), a AS (
                INSERT INTO architectures (id, project_id, current_revision)
                SELECT '00000000-0000-7000-8000-000000000003', p.id, 1 FROM p RETURNING id, project_id
            )
            INSERT INTO architecture_revisions (id, architecture_id, project_id, number, ir,
                                                ir_schema_version, content_hash, source, summary)
            SELECT gen_random_uuid(), a.id, a.project_id, 1,
                   '{"schema_version": 1, "name": "Orders"}'::jsonb, 1,
                   repeat('a', 64), 'user', 'Created with 0 nodes and 0 connections.'
            FROM a
            """,
        )
    )

    command.upgrade(config, "head")

    rows = asyncio.run(
        _execute(
            empty_database_url,
            "SELECT a.name, a.status, a.current_revision, r.restored_from_number "
            "FROM architectures a JOIN architecture_revisions r ON r.architecture_id = a.id",
        )
    )
    assert rows == [("Orders", "active", 1, None)]
    command.downgrade(config, "0008")  # one architecture per project: downgrading is possible
    command.upgrade(config, "head")


def test_downgrading_discovery_leaves_migration_plans_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0020")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES - DISCOVERY_TABLES - DRIFT_TABLES - KNOWLEDGE_TABLES - AGENT_TABLES - DIFF_TABLES
    )
    assert "discovery_runs_guard" not in _functions(empty_database_url)
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_drift_leaves_discovery_runs_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0021")
    assert (
        _tables(empty_database_url)
        == ALL_TABLES - DRIFT_TABLES - KNOWLEDGE_TABLES - AGENT_TABLES - DIFF_TABLES
    )
    assert "drift_items_guard" not in _functions(empty_database_url)
    assert "requirement_sets_reject_change" in _functions(empty_database_url)  # still guards its tables
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_knowledge_leaves_drift_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0022")
    assert _tables(empty_database_url) == ALL_TABLES - KNOWLEDGE_TABLES - AGENT_TABLES - DIFF_TABLES
    assert "knowledge_sources_guard" not in _functions(empty_database_url)
    assert "requirement_sets_reject_change" in _functions(empty_database_url)  # still guards its tables
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_the_agent_leaves_knowledge_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0023")
    assert _tables(empty_database_url) == ALL_TABLES - AGENT_TABLES - DIFF_TABLES
    assert "architecture_agent_runs_guard" not in _functions(empty_database_url)
    assert "knowledge_sources_guard" in _functions(empty_database_url)  # still guards its tables
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES


def test_downgrading_diffs_leaves_agent_runs_intact(empty_database_url: str) -> None:
    config = alembic_config(empty_database_url)
    command.upgrade(config, "head")
    command.downgrade(config, "0024")
    assert _tables(empty_database_url) == ALL_TABLES - DIFF_TABLES
    assert "architecture_diffs_reject_change" not in _functions(empty_database_url)
    assert "architecture_agent_runs_guard" in _functions(empty_database_url)  # still guards its table
    command.upgrade(config, "head")
    assert _tables(empty_database_url) == ALL_TABLES
