"""An evolution candidate: a proposed set of configuration changes to one exact baseline revision,
generated by one versioned rule from current evidence — a proposal, never applied by the engine.

- The **baseline** is the architecture, revision number and content hash the candidate is against.
- The **changes** are configuration changes of existing nodes and connections (the simulation's
  ``ConfigurationChange``, validated by the Architecture IR's property specifications). They are
  applied only to an in-memory overlay; the canonical architecture is never modified.
- **Evidence** references say which stored analysis (revision, content hash, model version), which
  finding or scaling option, requirement or goal the candidate rests on. Only ``current`` evidence
  (of the baseline's exact content) can support a candidate.
- **Effects** (benefits, trade-offs, operational complexity, migration considerations, risks) each
  state their dimension and their basis: ``modeled`` by an engine, stated by the ``rule``, or a
  ``consideration`` for human review. Nothing is scored, weighted or ranked.
- The **id** is derived from the rule, the baseline and the changes: the same proposal always has
  the same id.
"""

import hashlib
import json
import re
import uuid
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Self

from core.domain.engine_results import Evidence, read_evidence
from core.domain.errors import DomainError
from core.domain.simulations.scenarios import MAX_CHANGES, ConfigurationChange

from .errors import InvalidEvolutionResult
from .values import Basis, CandidateCategory, EvidenceSource, EvidenceState, ProposalStatus, ValidationState

CODE = re.compile(r"^[a-z][a-z0-9_.-]{0,63}$")
FINGERPRINT = re.compile(r"^[0-9a-f]{64}$")
CANDIDATE_ID = re.compile(r"^evo_[0-9a-f]{20}$")
MAX_TITLE = 200
MAX_TEXT = 2000
MAX_REFERENCE = 256
MAX_ITEMS = 200  # evidence, effects, goals and unknowns of one candidate


def _check(problems: list[str | None]) -> None:
    found = [p for p in problems if p]
    if found:
        raise InvalidEvolutionResult(details={"fields": found})


def _text(value: object, name: str, limit: int = MAX_TEXT, *, required: bool = True) -> str | None:
    if value is None and not required:
        return None
    return None if isinstance(value, str) and value.strip() and len(value) <= limit else name


def _code(value: object, name: str) -> str | None:
    return None if isinstance(value, str) and CODE.fullmatch(value) else name


def _strings(values: object, name: str) -> str | None:
    if not isinstance(values, tuple) or len(values) > MAX_ITEMS:
        return name
    return None if all(isinstance(v, str) and 0 < len(v) <= MAX_REFERENCE for v in values) else name


def _items(values: object, kind: type, name: str, *, limit: int = MAX_ITEMS) -> str | None:
    ok = isinstance(values, tuple) and len(values) <= limit and all(isinstance(v, kind) for v in values)
    return None if ok else name


def _count(value: object) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and value >= 1


def _hash(value: object) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


@dataclass(frozen=True, slots=True)
class BaselineRef:
    """The exact revision an analysis and its candidates are against."""

    architecture_id: uuid.UUID
    revision_number: int
    content_hash: str

    def __post_init__(self) -> None:
        _check(
            [
                None if isinstance(self.architecture_id, uuid.UUID) else "baseline.architecture_id",
                None if _count(self.revision_number) else "baseline.revision_number",
                None
                if isinstance(self.content_hash, str) and FINGERPRINT.fullmatch(self.content_hash)
                else "baseline.content_hash",
            ]
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "architecture_id": str(self.architecture_id),
            "revision_number": self.revision_number,
            "content_hash": self.content_hash,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(uuid.UUID(data["architecture_id"]), data["revision_number"], data["content_hash"])


@dataclass(frozen=True, slots=True)
class RuleRef:
    """The rule (and its version) that generated a candidate."""

    id: str
    version: int

    def __post_init__(self) -> None:
        _check([_code(self.id, "rule.id"), None if _count(self.version) else "rule.version"])

    def to_dict(self) -> dict[str, Any]:
        return {"id": self.id, "version": self.version}


@dataclass(frozen=True, slots=True)
class EvidenceRef:
    """One piece of evidence: its source, which record (``reference``: an analysis id, a requirement
    id or a goal key), which item of it (a finding id, a scaling option, a metric), and whether it is
    current for the baseline. Stored analyses also carry their revision, content hash and model
    version, so staleness is decided by content, not by date."""

    source: EvidenceSource
    reference: str
    state: EvidenceState
    item: str | None = None
    revision_number: int | None = None
    content_hash: str | None = None
    model_version: str | None = None

    def __post_init__(self) -> None:
        _check(
            [
                None if isinstance(self.source, EvidenceSource) else "evidence.source",
                _text(self.reference, "evidence.reference", MAX_REFERENCE),
                None if isinstance(self.state, EvidenceState) else "evidence.state",
                _text(self.item, "evidence.item", MAX_REFERENCE, required=False),
                None
                if self.revision_number is None or _count(self.revision_number)
                else "evidence.revision_number",
                None
                if self.content_hash is None
                or (isinstance(self.content_hash, str) and FINGERPRINT.fullmatch(self.content_hash))
                else "evidence.content_hash",
                _text(self.model_version, "evidence.model_version", 64, required=False),
            ]
        )

    @property
    def key(self) -> tuple[str, str, str]:
        return (self.source.value, self.reference, self.item or "")

    def to_dict(self) -> dict[str, Any]:
        return {
            "source": self.source.value,
            "reference": self.reference,
            "state": self.state.value,
            "item": self.item,
            "revision_number": self.revision_number,
            "content_hash": self.content_hash,
            "model_version": self.model_version,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            EvidenceSource(data["source"]),
            data["reference"],
            EvidenceState(data["state"]),
            data.get("item"),
            data.get("revision_number"),
            data.get("content_hash"),
            data.get("model_version"),
        )


@dataclass(frozen=True, slots=True)
class Effect:
    """A stated consequence of a candidate in one dimension (capacity, cost, reliability, security,
    observability, operations, migration, …), with what it rests on."""

    dimension: str
    code: str
    statement: str
    basis: Basis
    evidence: tuple[Evidence, ...] = ()

    def __post_init__(self) -> None:
        _check(
            [
                _code(self.dimension, "effect.dimension"),
                _code(self.code, "effect.code"),
                _text(self.statement, "effect.statement"),
                None if isinstance(self.basis, Basis) else "effect.basis",
                _items(self.evidence, Evidence, "effect.evidence"),
            ]
        )

    @property
    def key(self) -> tuple[str, str]:
        return (self.dimension, self.code)

    def to_dict(self) -> dict[str, Any]:
        return {
            "dimension": self.dimension,
            "code": self.code,
            "statement": self.statement,
            "basis": self.basis.value,
            "evidence": [e.to_dict() for e in self.evidence],
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            data["dimension"],
            data["code"],
            data["statement"],
            Basis(data["basis"]),
            read_evidence(data.get("evidence")),
        )


@dataclass(frozen=True, slots=True)
class ImpactRef:
    """An engine's evaluation of a candidate against the baseline: which engine, what it could
    establish (its own state), and the fingerprint of its result."""

    source: EvidenceSource
    state: str
    fingerprint: str | None = None
    model_version: str | None = None

    def __post_init__(self) -> None:
        _check(
            [
                None if isinstance(self.source, EvidenceSource) else "impact.source",
                _code(self.state, "impact.state"),
                None
                if self.fingerprint is None
                or (isinstance(self.fingerprint, str) and FINGERPRINT.fullmatch(self.fingerprint))
                else "impact.fingerprint",
                _text(self.model_version, "impact.model_version", 64, required=False),
            ]
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "source": self.source.value,
            "state": self.state,
            "fingerprint": self.fingerprint,
            "model_version": self.model_version,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            EvidenceSource(data["source"]), data["state"], data.get("fingerprint"), data.get("model_version")
        )


_EFFECTS = ("benefits", "tradeoffs", "complexity", "migration", "risks")


@dataclass(frozen=True, slots=True)
class Candidate:
    rule: RuleRef
    baseline: BaselineRef
    category: CandidateCategory
    title: str
    description: str
    changes: tuple[ConfigurationChange, ...]
    goals: tuple[str, ...]  # the keys of the goals it addresses
    rationale: str
    evidence: tuple[EvidenceRef, ...]
    benefits: tuple[Effect, ...] = ()
    tradeoffs: tuple[Effect, ...] = ()
    complexity: tuple[Effect, ...] = ()  # operational complexity implications
    migration: tuple[Effect, ...] = ()  # migration considerations (not a plan)
    risks: tuple[Effect, ...] = ()  # risks and failure modes it may add
    missing: tuple[str, ...] = ()  # what is unknown about it, and would decide it
    validation: ValidationState = ValidationState.NOT_VALIDATED
    impacts: tuple[ImpactRef, ...] = ()
    status: ProposalStatus = ProposalStatus.PROPOSED

    def __post_init__(self) -> None:
        self._canonical()
        _check(
            [
                None if isinstance(self.rule, RuleRef) else "rule",
                None if isinstance(self.baseline, BaselineRef) else "baseline",
                None if isinstance(self.category, CandidateCategory) else "category",
                _text(self.title, "title", MAX_TITLE),
                _text(self.description, "description"),
                None
                if isinstance(self.changes, tuple) and 0 < len(self.changes) <= MAX_CHANGES
                else "changes",
                _items(self.changes, ConfigurationChange, "changes", limit=MAX_CHANGES),
                None if len({c.key for c in self.changes}) == len(self.changes) else "changes.duplicate",
                None if self.goals and _strings(self.goals, "goals") is None else "goals",
                _text(self.rationale, "rationale"),
                None
                if self.evidence and _items(self.evidence, EvidenceRef, "evidence") is None
                else "evidence",
                None
                if all(e.state is EvidenceState.CURRENT for e in self.evidence)
                else "evidence.not_current",  # stale or missing evidence never supports a candidate
                *(_items(getattr(self, name), Effect, name) for name in _EFFECTS),
                _strings(self.missing, "missing"),
                None if isinstance(self.validation, ValidationState) else "validation",
                _items(self.impacts, ImpactRef, "impacts"),
                None if self.status is ProposalStatus.PROPOSED else "status",
            ]
        )

    def _canonical(self) -> None:
        sort = object.__setattr__
        if isinstance(self.changes, tuple) and all(isinstance(c, ConfigurationChange) for c in self.changes):
            sort(self, "changes", tuple(sorted(self.changes, key=lambda c: c.key)))
        if isinstance(self.goals, tuple) and all(isinstance(g, str) for g in self.goals):
            sort(self, "goals", tuple(sorted(set(self.goals))))
        if isinstance(self.missing, tuple) and all(isinstance(m, str) for m in self.missing):
            sort(self, "missing", tuple(sorted(set(self.missing))))
        if isinstance(self.evidence, tuple) and all(isinstance(e, EvidenceRef) for e in self.evidence):
            sort(self, "evidence", tuple(sorted(set(self.evidence), key=lambda e: e.key)))
        for name in _EFFECTS:
            effects = getattr(self, name)
            if isinstance(effects, tuple) and all(isinstance(e, Effect) for e in effects):
                sort(self, name, tuple(sorted(set(effects), key=lambda e: e.key)))
        if isinstance(self.impacts, tuple) and all(isinstance(i, ImpactRef) for i in self.impacts):
            sort(self, "impacts", tuple(sorted(set(self.impacts), key=lambda i: i.source.value)))

    @property
    def id(self) -> str:
        """Stable: the same rule, baseline and changes always make the same candidate id."""
        identity = {
            "rule": self.rule.to_dict(),
            "baseline": self.baseline.to_dict(),
            "category": self.category.value,
            "changes": [c.to_dict() for c in self.changes],
        }
        return f"evo_{_hash(identity)[:20]}"

    @property
    def element_ids(self) -> tuple[str, ...]:
        return tuple(sorted({c.element_id for c in self.changes}))

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "status": self.status.value,
            "rule": self.rule.to_dict(),
            "baseline": self.baseline.to_dict(),
            "category": self.category.value,
            "title": self.title,
            "description": self.description,
            "changes": [c.to_dict() for c in self.changes],
            "goals": list(self.goals),
            "rationale": self.rationale,
            "evidence": [e.to_dict() for e in self.evidence],
            **{name: [e.to_dict() for e in getattr(self, name)] for name in _EFFECTS},
            "missing": list(self.missing),
            "validation": self.validation.value,
            "impacts": [i.to_dict() for i in self.impacts],
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        """A candidate from its stored form; its id must be the one its content derives."""
        try:
            candidate = cls(
                rule=RuleRef(data["rule"]["id"], data["rule"]["version"]),
                baseline=BaselineRef.from_dict(data["baseline"]),
                category=CandidateCategory(data["category"]),
                title=data["title"],
                description=data["description"],
                changes=tuple(ConfigurationChange.from_dict(c) for c in data["changes"]),
                goals=tuple(data["goals"]),
                rationale=data["rationale"],
                evidence=tuple(EvidenceRef.from_dict(e) for e in data["evidence"]),
                **{name: tuple(Effect.from_dict(e) for e in data.get(name) or ()) for name in _EFFECTS},
                missing=tuple(data.get("missing") or ()),
                validation=ValidationState(data.get("validation", ValidationState.NOT_VALIDATED.value)),
                impacts=tuple(ImpactRef.from_dict(i) for i in data.get("impacts") or ()),
                status=ProposalStatus(data.get("status", ProposalStatus.PROPOSED.value)),
            )
        except InvalidEvolutionResult:
            raise
        except (DomainError, KeyError, TypeError, ValueError) as error:
            raise InvalidEvolutionResult(details={"fields": [type(error).__name__]}) from None
        if data.get("id") not in (None, candidate.id):
            raise InvalidEvolutionResult(details={"fields": ["id"]})
        return candidate
