"""An evolution candidate: a proposed set of configuration changes to one exact baseline revision,
generated by one versioned rule from current evidence — a proposal, never applied by the engine.

- The **baseline** is the architecture, revision number and content hash the candidate is against.
- The **changes** are configuration changes of existing nodes and connections (the simulation's
  ``ConfigurationChange``, validated by the Architecture IR's property specifications). They are
  applied only to an in-memory overlay; the canonical architecture is never modified.
- **Evidence** references say which stored analysis (revision, content hash, model version), which
  finding or scaling option, requirement or goal the candidate rests on. Only ``current`` evidence
  (of the baseline's exact content) can support a candidate.
- **Effects** (benefits, trade-offs, operational complexity, migration considerations, risks) each
  state their dimension and their basis: ``modeled`` by an engine, stated by the ``rule``, or a
  ``consideration`` for human review. Nothing is scored, weighted or ranked.
- The **id** is derived from the rule, the baseline and the changes: the same proposal always has
  the same id.
"""

import hashlib
import json
import re
import uuid
from collections.abc import Mapping
from dataclasses import dataclass
from typing import Any, Self

from core.domain.engine_results import Evidence, read_evidence
from core.domain.errors import DomainError
from core.domain.simulations.scenarios import MAX_CHANGES, ConfigurationChange

from .errors import InvalidEvolutionResult
from .values import (
    Basis,
    CandidateCategory,
    Direction,
    EvidenceSource,
    EvidenceState,
    ProposalStatus,
    ValidationState,
)

CODE = re.compile(r"^[a-z][a-z0-9_.-]{0,63}$")
FINGERPRINT = re.compile(r"^[0-9a-f]{64}$")
CANDIDATE_ID = re.compile(r"^evo_[0-9a-f]{20}$")
MAX_TITLE = 200
MAX_TEXT = 2000
MAX_REFERENCE = 256
MAX_ITEMS = 200  # evidence, effects, goals and unknowns of one candidate


def _check(problems: list[str | None]) -> None:
    found = [p for p in problems if p]
    if found:
        raise InvalidEvolutionResult(details={"fields": found})


def _text(value: object, name: str, limit: int = MAX_TEXT, *, required: bool = True) -> str | None:
    if value is None and not required:
        return None
    return None if isinstance(value, str) and value.strip() and len(value) <= limit else name


def _code(value: object, name: str) -> str | None:
    return None if isinstance(value, str) and CODE.fullmatch(value) else name


def _strings(values: object, name: str) -> str | None:
    if not isinstance(values, tuple) or len(values) > MAX_ITEMS:
        return name
    return None if all(isinstance(v, str) and 0 < len(v) <= MAX_REFERENCE for v in values) else name


def _items(values: object, kind: type, name: str, *, limit: int = MAX_ITEMS) -> str | None:
    ok = isinstance(values, tuple) and len(values) <= limit and all(isinstance(v, kind) for v in values)
    return None if ok else name


def _count(value: object) -> bool:
    return isinstance(value, int) and not isinstance(value, bool) and value >= 1


def _hash(value: object) -> str:
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


@dataclass(frozen=True, slots=True)
class BaselineRef:
    """The exact revision an analysis and its candidates are against."""

    architecture_id: uuid.UUID
    revision_number: int
    content_hash: str

    def __post_init__(self) -> None:
        _check(
            [
                None if isinstance(self.architecture_id, uuid.UUID) else "baseline.architecture_id",
                None if _count(self.revision_number) else "baseline.revision_number",
                None
                if isinstance(self.content_hash, str) and FINGERPRINT.fullmatch(self.content_hash)
                else "baseline.content_hash",
            ]
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "architecture_id": str(self.architecture_id),
            "revision_number": self.revision_number,
            "content_hash": self.content_hash,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(uuid.UUID(data["architecture_id"]), data["revision_number"], data["content_hash"])


@dataclass(frozen=True, slots=True)
class RuleRef:
    """The rule (and its version) that generated a candidate."""

    id: str
    version: int

    def __post_init__(self) -> None:
        _check([_code(self.id, "rule.id"), None if _count(self.version) else "rule.version"])

    def to_dict(self) -> dict[str, Any]:
        return {"id": self.id, "version": self.version}


@dataclass(frozen=True, slots=True)
class EvidenceRef:
    """One piece of evidence: its source, which record (``reference``: an analysis id, a requirement
    id or a goal key), which item of it (a finding id, a scaling option, a metric), and whether it is
    current for the baseline. Stored analyses also carry their revision, content hash and model
    version, so staleness is decided by content, not by date."""

    source: EvidenceSource
    reference: str
    state: EvidenceState
    item: str | None = None
    revision_number: int | None = None
    content_hash: str | None = None
    model_version: str | None = None

    def __post_init__(self) -> None:
        _check(
            [
                None if isinstance(self.source, EvidenceSource) else "evidence.source",
                _text(self.reference, "evidence.reference", MAX_REFERENCE),
                None if isinstance(self.state, EvidenceState) else "evidence.state",
                _text(self.item, "evidence.item", MAX_REFERENCE, required=False),
                None
                if self.revision_number is None or _count(self.revision_number)
                else "evidence.revision_number",
                None
                if self.content_hash is None
                or (isinstance(self.content_hash, str) and FINGERPRINT.fullmatch(self.content_hash))
                else "evidence.content_hash",
                _text(self.model_version, "evidence.model_version", 64, required=False),
            ]
        )

    @property
    def key(self) -> tuple[str, str, str]:
        return (self.source.value, self.reference, self.item or "")

    def to_dict(self) -> dict[str, Any]:
        return {
            "source": self.source.value,
            "reference": self.reference,
            "state": self.state.value,
            "item": self.item,
            "revision_number": self.revision_number,
            "content_hash": self.content_hash,
            "model_version": self.model_version,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            EvidenceSource(data["source"]),
            data["reference"],
            EvidenceState(data["state"]),
            data.get("item"),
            data.get("revision_number"),
            data.get("content_hash"),
            data.get("model_version"),
        )


@dataclass(frozen=True, slots=True)
class Effect:
    """A stated consequence of a candidate in one dimension (capacity, cost, reliability, security,
    observability, operations, migration, …), with what it rests on."""

    dimension: str
    code: str
    statement: str
    basis: Basis
    evidence: tuple[Evidence, ...] = ()

    def __post_init__(self) -> None:
        _check(
            [
                _code(self.dimension, "effect.dimension"),
                _code(self.code, "effect.code"),
                _text(self.statement, "effect.statement"),
                None if isinstance(self.basis, Basis) else "effect.basis",
                _items(self.evidence, Evidence, "effect.evidence"),
            ]
        )

    @property
    def key(self) -> tuple[str, str]:
        return (self.dimension, self.code)

    def to_dict(self) -> dict[str, Any]:
        return {
            "dimension": self.dimension,
            "code": self.code,
            "statement": self.statement,
            "basis": self.basis.value,
            "evidence": [e.to_dict() for e in self.evidence],
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            data["dimension"],
            data["code"],
            data["statement"],
            Basis(data["basis"]),
            read_evidence(data.get("evidence")),
        )


MAX_DELTAS = 500  # per impact: bounded by the architecture's size, cut in canonical order


def _fingerprint(value: object, name: str) -> str | None:
    if value is None:
        return None
    return None if isinstance(value, str) and FINGERPRINT.fullmatch(value) else name


@dataclass(frozen=True, slots=True)
class ImpactDelta:
    """One metric of one element (or ``system``), baseline versus candidate, in one unit: exact
    decimal strings, ``None`` when unknown; a difference only when both are known."""

    element_id: str
    metric: str
    unit: str
    baseline: str | None
    candidate: str | None
    difference: str | None = None
    percentage: str | None = None
    comparable: bool = True
    note: str | None = None

    def __post_init__(self) -> None:
        _check(
            [
                _text(self.element_id, "delta.element_id", MAX_REFERENCE),
                _text(self.metric, "delta.metric", MAX_REFERENCE),
                _text(self.unit, "delta.unit", 64),
                None
                if self.difference is None or (self.baseline is not None and self.candidate is not None)
                else "delta.difference",
                None if isinstance(self.comparable, bool) else "delta.comparable",
                _text(self.note, "delta.note", MAX_REFERENCE, required=False),
            ]
        )

    @property
    def key(self) -> tuple[str, str]:
        return (self.element_id, self.metric)

    def to_dict(self) -> dict[str, Any]:
        return {
            "element_id": self.element_id,
            "metric": self.metric,
            "unit": self.unit,
            "baseline": self.baseline,
            "candidate": self.candidate,
            "difference": self.difference,
            "percentage": self.percentage,
            "comparable": self.comparable,
            "note": self.note,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            data["element_id"],
            data["metric"],
            data["unit"],
            data.get("baseline"),
            data.get("candidate"),
            data.get("difference"),
            data.get("percentage"),
            bool(data.get("comparable", True)),
            data.get("note"),
        )


@dataclass(frozen=True, slots=True)
class ImpactChange:
    """A finding the candidate resolves or introduces, by the engine's stable finding id."""

    kind: str  # resolved, introduced
    reference: str
    code: str  # the finding type
    element_ids: tuple[str, ...] = ()
    severity: str | None = None

    def __post_init__(self) -> None:
        if isinstance(self.element_ids, tuple) and all(isinstance(e, str) for e in self.element_ids):
            object.__setattr__(self, "element_ids", tuple(sorted(set(self.element_ids))))
        _check(
            [
                None if self.kind in ("resolved", "introduced") else "change.kind",
                _text(self.reference, "change.reference", MAX_REFERENCE),
                _code(self.code, "change.code"),
                _strings(self.element_ids, "change.element_ids"),
                _text(self.severity, "change.severity", 32, required=False),
            ]
        )

    @property
    def key(self) -> tuple[str, str]:
        return (self.kind, self.reference)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "reference": self.reference,
            "code": self.code,
            "element_ids": list(self.element_ids),
            "severity": self.severity,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            data["kind"],
            data["reference"],
            data["code"],
            tuple(data.get("element_ids") or ()),
            data.get("severity"),
        )


@dataclass(frozen=True, slots=True)
class Impact:
    """One dimension of a candidate's impact, as the engine that evaluates it established it on the
    baseline and on the candidate's overlay, with the same inputs: its state (the engine's own, or
    ``unsupported`` / ``not_evaluated`` with the reason), the engine (``source``) and model version,
    the baseline and candidate result fingerprints, the stored analyses whose inputs were reused,
    what differs, the assumptions, and what is unknown. Dimensions are never combined."""

    dimension: EvidenceSource
    state: str
    source: EvidenceSource
    reason: str | None = None
    baseline_fingerprint: str | None = None
    candidate_fingerprint: str | None = None
    model_version: str | None = None
    inputs: tuple[EvidenceRef, ...] = ()
    deltas: tuple[ImpactDelta, ...] = ()
    changes: tuple[ImpactChange, ...] = ()
    assumptions: tuple[Evidence, ...] = ()
    missing: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        sort = object.__setattr__
        if isinstance(self.deltas, tuple) and all(isinstance(d, ImpactDelta) for d in self.deltas):
            sort(self, "deltas", tuple(sorted(set(self.deltas), key=lambda d: d.key)))
        if isinstance(self.changes, tuple) and all(isinstance(c, ImpactChange) for c in self.changes):
            sort(self, "changes", tuple(sorted(set(self.changes), key=lambda c: c.key)))
        if isinstance(self.inputs, tuple) and all(isinstance(e, EvidenceRef) for e in self.inputs):
            sort(self, "inputs", tuple(sorted(set(self.inputs), key=lambda e: e.key)))
        if isinstance(self.missing, tuple) and all(isinstance(m, str) for m in self.missing):
            sort(self, "missing", tuple(sorted(set(self.missing))))
        _check(
            [
                None if isinstance(self.dimension, EvidenceSource) else "impact.dimension",
                _code(self.state, "impact.state"),
                None if isinstance(self.source, EvidenceSource) else "impact.source",
                _code(self.reason, "impact.reason") if self.reason is not None else None,
                _fingerprint(self.baseline_fingerprint, "impact.baseline_fingerprint"),
                _fingerprint(self.candidate_fingerprint, "impact.candidate_fingerprint"),
                _text(self.model_version, "impact.model_version", 64, required=False),
                _items(self.inputs, EvidenceRef, "impact.inputs"),
                _items(self.deltas, ImpactDelta, "impact.deltas", limit=MAX_DELTAS),
                _items(self.changes, ImpactChange, "impact.changes"),
                _items(self.assumptions, Evidence, "impact.assumptions"),
                _strings(self.missing, "impact.missing"),
            ]
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "dimension": self.dimension.value,
            "state": self.state,
            "source": self.source.value,
            "reason": self.reason,
            "baseline_fingerprint": self.baseline_fingerprint,
            "candidate_fingerprint": self.candidate_fingerprint,
            "model_version": self.model_version,
            "inputs": [e.to_dict() for e in self.inputs],
            "deltas": [d.to_dict() for d in self.deltas],
            "changes": [c.to_dict() for c in self.changes],
            "assumptions": [e.to_dict() for e in self.assumptions],
            "missing": list(self.missing),
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            EvidenceSource(data["dimension"]),
            data["state"],
            EvidenceSource(data["source"]),
            data.get("reason"),
            data.get("baseline_fingerprint"),
            data.get("candidate_fingerprint"),
            data.get("model_version"),
            tuple(EvidenceRef.from_dict(e) for e in data.get("inputs") or ()),
            tuple(ImpactDelta.from_dict(d) for d in data.get("deltas") or ()),
            tuple(ImpactChange.from_dict(c) for c in data.get("changes") or ()),
            read_evidence(data.get("assumptions")),
            tuple(data.get("missing") or ()),
        )


@dataclass(frozen=True, slots=True)
class ValidationNote:
    """One thing validation established about a candidate: a finding the overlay introduces or
    resolves, a requirement it violates or leaves unverifiable, a rule that could not run, or why the
    overlay was refused — with the exact elements concerned."""

    code: str  # introduced_finding, resolved_finding, requirement_violated, requirement_not_verifiable,
    # rule_failed, overlay_refused
    message: str
    reference: str | None = None  # the finding, requirement or rule id
    element_ids: tuple[str, ...] = ()
    blocking: bool = False

    def __post_init__(self) -> None:
        if isinstance(self.element_ids, tuple) and all(isinstance(e, str) for e in self.element_ids):
            object.__setattr__(self, "element_ids", tuple(sorted(set(self.element_ids))))
        _check(
            [
                _code(self.code, "validation.code"),
                _text(self.message, "validation.message"),
                _text(self.reference, "validation.reference", MAX_REFERENCE, required=False),
                _strings(self.element_ids, "validation.element_ids"),
                None if isinstance(self.blocking, bool) else "validation.blocking",
            ]
        )

    @property
    def key(self) -> tuple[str, str, tuple[str, ...]]:
        return (self.code, self.reference or "", self.element_ids)

    def to_dict(self) -> dict[str, Any]:
        return {
            "code": self.code,
            "message": self.message,
            "reference": self.reference,
            "element_ids": list(self.element_ids),
            "blocking": self.blocking,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            data["code"],
            data["message"],
            data.get("reference"),
            tuple(data.get("element_ids") or ()),
            bool(data.get("blocking", False)),
        )


@dataclass(frozen=True, slots=True)
class Consequence:
    """How a candidate moves one dimension (capacity, cost, reliability, security, observability,
    operations, migration, dependencies, failure_modes, reversibility, expertise): its direction, what
    that rests on (``modeled`` by an engine, stated by a ``rule``, or a ``consideration`` for human
    review), a sentence, and the evidence. Consequences are never weighted or added up."""

    dimension: str
    direction: Direction
    basis: Basis
    statement: str
    evidence: tuple[Evidence, ...] = ()

    def __post_init__(self) -> None:
        _check(
            [
                _code(self.dimension, "consequence.dimension"),
                None if isinstance(self.direction, Direction) else "consequence.direction",
                None if isinstance(self.basis, Basis) else "consequence.basis",
                _text(self.statement, "consequence.statement"),
                _items(self.evidence, Evidence, "consequence.evidence"),
                self._basis_problem(),
            ]
        )

    def _basis_problem(self) -> str | None:
        """A model never yields a mere consideration; a consideration never decides a direction."""
        if self.basis is Basis.MODELED and self.direction is Direction.CONSIDERATION:
            return "consequence.basis"
        if self.basis is Basis.CONSIDERATION and self.direction is not Direction.CONSIDERATION:
            return "consequence.basis"
        return None

    def to_dict(self) -> dict[str, Any]:
        return {
            "dimension": self.dimension,
            "direction": self.direction.value,
            "basis": self.basis.value,
            "statement": self.statement,
            "evidence": [e.to_dict() for e in self.evidence],
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        return cls(
            data["dimension"],
            Direction(data["direction"]),
            Basis(data["basis"]),
            data["statement"],
            read_evidence(data.get("evidence")),
        )


_EFFECTS = ("benefits", "tradeoffs", "complexity", "migration", "risks")


@dataclass(frozen=True, slots=True)
class Candidate:
    rule: RuleRef
    baseline: BaselineRef
    category: CandidateCategory
    title: str
    description: str
    changes: tuple[ConfigurationChange, ...]
    goals: tuple[str, ...]  # the keys of the goals it addresses
    rationale: str
    evidence: tuple[EvidenceRef, ...]
    benefits: tuple[Effect, ...] = ()
    tradeoffs: tuple[Effect, ...] = ()
    complexity: tuple[Effect, ...] = ()  # operational complexity implications
    migration: tuple[Effect, ...] = ()  # migration considerations (not a plan)
    risks: tuple[Effect, ...] = ()  # risks and failure modes it may add
    missing: tuple[str, ...] = ()  # what is unknown about it, and would decide it
    validation: ValidationState = ValidationState.NOT_VALIDATED
    validation_notes: tuple[ValidationNote, ...] = ()
    impacts: tuple[Impact, ...] = ()
    consequences: tuple[Consequence, ...] = ()  # the trade-off table, one row per dimension
    status: ProposalStatus = ProposalStatus.PROPOSED

    def __post_init__(self) -> None:
        self._canonical()
        _check(
            [
                None if isinstance(self.rule, RuleRef) else "rule",
                None if isinstance(self.baseline, BaselineRef) else "baseline",
                None if isinstance(self.category, CandidateCategory) else "category",
                _text(self.title, "title", MAX_TITLE),
                _text(self.description, "description"),
                None
                if isinstance(self.changes, tuple) and 0 < len(self.changes) <= MAX_CHANGES
                else "changes",
                _items(self.changes, ConfigurationChange, "changes", limit=MAX_CHANGES),
                None if len({c.key for c in self.changes}) == len(self.changes) else "changes.duplicate",
                None if self.goals and _strings(self.goals, "goals") is None else "goals",
                _text(self.rationale, "rationale"),
                None
                if self.evidence and _items(self.evidence, EvidenceRef, "evidence") is None
                else "evidence",
                None
                if all(e.state is EvidenceState.CURRENT for e in self.evidence)
                else "evidence.not_current",  # stale or missing evidence never supports a candidate
                *(_items(getattr(self, name), Effect, name) for name in _EFFECTS),
                _strings(self.missing, "missing"),
                None if isinstance(self.validation, ValidationState) else "validation",
                _items(self.validation_notes, ValidationNote, "validation_notes"),
                _items(self.impacts, Impact, "impacts"),
                _items(self.consequences, Consequence, "consequences"),
                None
                if len({c.dimension for c in self.consequences}) == len(self.consequences)
                else "consequences.duplicate",
                None if self.status is ProposalStatus.PROPOSED else "status",
            ]
        )

    def _canonical(self) -> None:
        sort = object.__setattr__
        if isinstance(self.changes, tuple) and all(isinstance(c, ConfigurationChange) for c in self.changes):
            sort(self, "changes", tuple(sorted(self.changes, key=lambda c: c.key)))
        if isinstance(self.goals, tuple) and all(isinstance(g, str) for g in self.goals):
            sort(self, "goals", tuple(sorted(set(self.goals))))
        if isinstance(self.missing, tuple) and all(isinstance(m, str) for m in self.missing):
            sort(self, "missing", tuple(sorted(set(self.missing))))
        if isinstance(self.evidence, tuple) and all(isinstance(e, EvidenceRef) for e in self.evidence):
            sort(self, "evidence", tuple(sorted(set(self.evidence), key=lambda e: e.key)))
        for name in _EFFECTS:
            effects = getattr(self, name)
            if isinstance(effects, tuple) and all(isinstance(e, Effect) for e in effects):
                sort(self, name, tuple(sorted(set(effects), key=lambda e: e.key)))
        notes = self.validation_notes
        if isinstance(notes, tuple) and all(isinstance(n, ValidationNote) for n in notes):
            sort(self, "validation_notes", tuple(sorted(set(notes), key=lambda n: n.key)))
        consequences = self.consequences
        if isinstance(consequences, tuple) and all(isinstance(c, Consequence) for c in consequences):
            sort(self, "consequences", tuple(sorted(consequences, key=lambda c: c.dimension)))
        if isinstance(self.impacts, tuple) and all(isinstance(i, Impact) for i in self.impacts):
            sort(self, "impacts", tuple(sorted(self.impacts, key=lambda i: i.dimension.value)))

    @property
    def id(self) -> str:
        """Stable: the same rule, baseline and changes always make the same candidate id."""
        identity = {
            "rule": self.rule.to_dict(),
            "baseline": self.baseline.to_dict(),
            "category": self.category.value,
            "changes": [c.to_dict() for c in self.changes],
        }
        return f"evo_{_hash(identity)[:20]}"

    @property
    def element_ids(self) -> tuple[str, ...]:
        return tuple(sorted({c.element_id for c in self.changes}))

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "status": self.status.value,
            "rule": self.rule.to_dict(),
            "baseline": self.baseline.to_dict(),
            "category": self.category.value,
            "title": self.title,
            "description": self.description,
            "changes": [c.to_dict() for c in self.changes],
            "goals": list(self.goals),
            "rationale": self.rationale,
            "evidence": [e.to_dict() for e in self.evidence],
            **{name: [e.to_dict() for e in getattr(self, name)] for name in _EFFECTS},
            "missing": list(self.missing),
            "validation": self.validation.value,
            "validation_notes": [n.to_dict() for n in self.validation_notes],
            "impacts": [i.to_dict() for i in self.impacts],
            "consequences": [c.to_dict() for c in self.consequences],
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        """A candidate from its stored form; its id must be the one its content derives."""
        try:
            candidate = cls(
                rule=RuleRef(data["rule"]["id"], data["rule"]["version"]),
                baseline=BaselineRef.from_dict(data["baseline"]),
                category=CandidateCategory(data["category"]),
                title=data["title"],
                description=data["description"],
                changes=tuple(ConfigurationChange.from_dict(c) for c in data["changes"]),
                goals=tuple(data["goals"]),
                rationale=data["rationale"],
                evidence=tuple(EvidenceRef.from_dict(e) for e in data["evidence"]),
                **{name: tuple(Effect.from_dict(e) for e in data.get(name) or ()) for name in _EFFECTS},
                missing=tuple(data.get("missing") or ()),
                validation=ValidationState(data.get("validation", ValidationState.NOT_VALIDATED.value)),
                validation_notes=tuple(
                    ValidationNote.from_dict(n) for n in data.get("validation_notes") or ()
                ),
                impacts=tuple(Impact.from_dict(i) for i in data.get("impacts") or ()),
                consequences=tuple(Consequence.from_dict(c) for c in data.get("consequences") or ()),
                status=ProposalStatus(data.get("status", ProposalStatus.PROPOSED.value)),
            )
        except InvalidEvolutionResult:
            raise
        except (DomainError, KeyError, TypeError, ValueError) as error:
            raise InvalidEvolutionResult(details={"fields": [type(error).__name__]}) from None
        if data.get("id") not in (None, candidate.id):
            raise InvalidEvolutionResult(details={"fields": ["id"]})
        return candidate
