"use client";

/**
 * Contextual right panel (spec §28): a component, a connection, a multi-selection,
 * or — with nothing selected — a summary of the architecture.
 */
import { Trash2, X } from "lucide-react";
import { useMemo } from "react";
import { useShallow } from "zustand/react/shallow";

import { type ProvenanceKind, ProvenanceTag } from "@/components/feedback/ProvenanceTag";
import { Button } from "@/components/ui/button";
import { IconButton } from "@/components/ui/icon-button";
import { formatRelativeTime } from "@/lib/formatting";
import { selectIsDirty, useArchitectureStore } from "@/stores/architecture-store";
import { useUiStore } from "@/stores/ui-store";
import { useWorkspaceStore } from "@/stores/workspace-store";
import type { AnalysisMode, Architecture, ArchitectureAuthor, Assumption } from "@/types/architecture";
import type { CapacityAnalysis } from "@/types/capacity";
import type { ComponentType } from "@/types/component";
import type { CostEstimate } from "@/types/cost";
import type { ObservabilityAnalysis } from "@/types/observability";
import type { SecurityAnalysis } from "@/types/security";
import type { Finding } from "@/types/validation";

import { COMPONENT_TYPE_META } from "../constants";
import type { ArchitectureCommand } from "../types";
import { STATUS_LABELS, toFlowNodes } from "../utils/node-transform";
import { ConnectionEditor } from "./ConnectionEditor";
import {
  type NodeCostDetails,
  NodeInspector,
  type NodeObservabilityDetails,
  type NodeSecurityDetails,
} from "./NodeInspector";

const AUTHOR_LABEL: Record<ArchitectureAuthor, string> = {
  ai: "Generated by ArchitectOS",
  user: "Saved by you",
  discovery: "Imported by discovery",
};

const ASSUMPTION_SOURCE: Record<Assumption["source"], { kind: ProvenanceKind; label: string }> = {
  user: { kind: "fact", label: "User" },
  ai: { kind: "ai", label: "AI assumption" },
  default: { kind: "fact", label: "Default" },
};

export interface ArchitectureInspectorProps {
  projectId: string;
  mode: AnalysisMode;
  capacity: CapacityAnalysis | null;
  findings: readonly Finding[];
  editable: boolean;
  onCommand: (command: ArchitectureCommand) => void;
  onDeleteSelection: () => void;
  onSelectNode: (nodeId: string) => void;
  security?: SecurityAnalysis | null;
  observability?: ObservabilityAnalysis | null;
  cost?: CostEstimate | null;
  /** A read-only historical version shown instead of the draft (`?version=N`). */
  architecture?: Architecture | null;
}

function securityFor(analysis: SecurityAnalysis | null, nodeId: string): NodeSecurityDetails | null {
  if (!analysis) return null;
  return {
    exposure: analysis.exposure.find((e) => e.nodeId === nodeId) ?? null,
    controls: analysis.controls.find((c) => c.nodeId === nodeId) ?? null,
    threats: analysis.threats.filter((t) => t.nodeIds.includes(nodeId)),
  };
}

function observabilityFor(
  analysis: ObservabilityAnalysis | null,
  nodeId: string,
): NodeObservabilityDetails | null {
  if (!analysis) return null;
  return {
    coverage: analysis.coverage.find((c) => c.nodeId === nodeId) ?? null,
    slos: analysis.slos.filter((slo) => slo.nodeIds.includes(nodeId)),
    gap: analysis.gaps.find((g) => g.nodeId === nodeId) ?? null,
  };
}

function costFor(estimate: CostEstimate | null, nodeId: string): NodeCostDetails | null {
  const cost = estimate?.nodes.find((n) => n.nodeId === nodeId);
  if (!estimate || !cost) return null;
  return { cost, currency: estimate.currency, evidenceId: estimate.evidenceIds[0] ?? null };
}

function ArchitectureSummary({ architecture, dirty }: { architecture: Architecture; dirty: boolean }) {
  const counts = useMemo(() => {
    const byType = new Map<ComponentType, number>();
    for (const node of architecture.nodes) byType.set(node.type, (byType.get(node.type) ?? 0) + 1);
    return [...byType].sort((a, b) => b[1] - a[1]);
  }, [architecture.nodes]);

  return (
    <div className="flex flex-col gap-5 px-4 py-3">
      <header className="flex flex-col gap-1">
        <span className="label-caps">Architecture</span>
        <p className="text-base font-semibold text-fg">
          <span className="tabular">v{architecture.version}</span>
          {dirty ? <span className="ml-2 text-xs font-normal text-warning-fg">Unsaved changes</span> : null}
        </p>
        <p className="text-xs text-muted">
          {AUTHOR_LABEL[architecture.createdBy]} · {formatRelativeTime(architecture.createdAt)}
        </p>
      </header>

      <section className="flex flex-col gap-1.5">
        <h3 className="label-caps">Components</h3>
        <dl className="divide-y divide-default">
          {counts.map(([type, count]) => {
            const { Icon, category } = COMPONENT_TYPE_META[type];
            return (
              <div key={type} className="flex items-center justify-between py-1.5 text-sm">
                <dt className="flex items-center gap-2 text-fg-secondary">
                  <Icon aria-hidden className="size-3.5 text-muted" />
                  {category}
                </dt>
                <dd className="tabular text-fg">{count}</dd>
              </div>
            );
          })}
          <div className="flex items-center justify-between py-1.5 text-sm">
            <dt className="text-fg-secondary">Connections</dt>
            <dd className="tabular text-fg">{architecture.edges.length}</dd>
          </div>
        </dl>
      </section>

      <section className="flex flex-col gap-1.5">
        <h3 className="label-caps">Assumptions</h3>
        {architecture.assumptions.length === 0 ? (
          <p className="text-xs text-muted">No assumptions recorded.</p>
        ) : (
          <ul className="flex flex-col gap-2">
            {architecture.assumptions.map((assumption) => {
              const source = ASSUMPTION_SOURCE[assumption.source];
              return (
                <li key={assumption.id} className="flex flex-col gap-1">
                  <div className="flex items-center gap-2">
                    <span className="tabular text-2xs text-muted">{assumption.id}</span>
                    <ProvenanceTag kind={source.kind} label={source.label} />
                  </div>
                  <p className="text-sm text-fg">{assumption.statement}</p>
                </li>
              );
            })}
          </ul>
        )}
      </section>

      <p className="text-xs text-muted">Select a component or connection to inspect it.</p>
    </div>
  );
}

export function ArchitectureInspector({
  projectId,
  mode,
  capacity,
  findings,
  editable,
  onCommand,
  onDeleteSelection,
  onSelectNode,
  security = null,
  observability = null,
  cost = null,
  architecture = null,
}: ArchitectureInspectorProps) {
  const draft = useArchitectureStore((s) => s.present);
  const draftDirty = useArchitectureStore(selectIsDirty);
  const present = architecture ?? draft;
  const dirty = architecture ? false : draftDirty;
  const { selectedNodeIds, selectedEdgeIds, tab, setTab, close } = useWorkspaceStore(
    useShallow((s) => ({
      selectedNodeIds: s.selectedNodeIds,
      selectedEdgeIds: s.selectedEdgeIds,
      tab: s.inspectorTab,
      setTab: s.setInspectorTab,
      close: s.closeInspector,
    })),
  );
  const openEvidence = useUiStore((s) => s.openEvidence);

  const nodeId =
    selectedNodeIds.length === 1 && selectedEdgeIds.length === 0 ? selectedNodeIds[0] : undefined;
  const edgeId =
    selectedNodeIds.length === 0 && selectedEdgeIds.length === 1 ? selectedEdgeIds[0] : undefined;
  const node = nodeId ? present?.nodes.find((n) => n.id === nodeId) : undefined;
  const edge = edgeId ? present?.edges.find((e) => e.id === edgeId) : undefined;

  const nodeDetails = useMemo(() => {
    if (!node) return null;
    const nodeFindings = findings.filter((f) => f.status === "open" && f.nodeIds.includes(node.id));
    const flow = toFlowNodes([node], {
      mode,
      capacity,
      findings: nodeFindings,
      highlightedNodeIds: new Set(),
      selectedNodeIds: new Set(),
      security,
      observability,
      cost,
    })[0];
    return {
      utilization: capacity?.utilization.filter((row) => row.nodeId === node.id) ?? [],
      findings: nodeFindings,
      status: flow?.data.status ?? "default",
      statusLabel: flow?.data.statusLabel ?? STATUS_LABELS.default,
      security: securityFor(security, node.id),
      observability: observabilityFor(observability, node.id),
      cost: costFor(cost, node.id),
    };
  }, [node, findings, capacity, mode, security, observability, cost]);

  let body: React.ReactNode;
  let title = "Architecture";
  if (!present) {
    body = null;
  } else if (node && nodeDetails) {
    title = "Component";
    body = (
      <NodeInspector
        key={node.id}
        projectId={projectId}
        node={node}
        architecture={present}
        utilization={nodeDetails.utilization}
        findings={nodeDetails.findings}
        status={nodeDetails.status}
        statusLabel={nodeDetails.statusLabel}
        security={nodeDetails.security}
        observability={nodeDetails.observability}
        cost={nodeDetails.cost}
        tab={tab}
        onTabChange={setTab}
        editable={editable}
        onCommand={onCommand}
        onOpenEvidence={openEvidence}
        onSelectNode={onSelectNode}
      />
    );
  } else if (edge) {
    title = "Connection";
    body = (
      <ConnectionEditor
        edge={edge}
        architecture={present}
        rps={capacity?.edges.find((e) => e.edgeId === edge.id)?.rps ?? null}
        editable={editable}
        onCommand={onCommand}
        onSelectNode={onSelectNode}
      />
    );
  } else if (selectedNodeIds.length + selectedEdgeIds.length > 1) {
    title = "Selection";
    body = (
      <div className="flex flex-col gap-3 px-4 py-3">
        <p className="text-sm text-fg">
          <span className="tabular">{selectedNodeIds.length}</span> components and{" "}
          <span className="tabular">{selectedEdgeIds.length}</span> connections selected.
        </p>
        {editable ? (
          <div>
            <Button size="sm" variant="danger" onClick={onDeleteSelection}>
              <Trash2 aria-hidden className="size-3.5" />
              Delete selection
            </Button>
          </div>
        ) : null}
      </div>
    );
  } else {
    body = <ArchitectureSummary architecture={present} dirty={dirty} />;
  }

  return (
    <div className="flex h-full min-h-0 flex-col">
      <div className="flex h-11 shrink-0 items-center justify-between border-b border-default pr-2 pl-4">
        <h2 className="label-caps">{title}</h2>
        <IconButton size="sm" label="Close inspector" shortcut="esc" onClick={close}>
          <X aria-hidden />
        </IconButton>
      </div>
      <div className="flex min-h-0 flex-1 flex-col overflow-y-auto">{body}</div>
    </div>
  );
}
